async browserPage => {
 const context=await browserPage.context().browser().newContext({viewport:{width:1440,height:960}}),checks=[],errors=[];
 const assert=(ok,label)=>{if(!ok)throw Error(label);checks.push(label);};
 await context.addInitScript(()=>{window.gardenInspect={};window.__THREE_DEVTOOLS__=new EventTarget();__THREE_DEVTOOLS__.addEventListener('observe',e=>{const v=e.detail;if(v.isScene)gardenInspect.scene=v;if(typeof v.render==='function'){const render=v.render.bind(v);let depth=0;v.render=(s,c)=>{if(!depth)gardenInspect.camera=c;depth++;try{return render(s,c);}finally{depth--;}};}});});
 const p=await context.newPage();p.on('pageerror',e=>errors.push(e.message));p.on('console',m=>{if(m.type()==='error')errors.push(m.text());});
 const pos=()=>p.evaluate(()=>gardenInspect.camera.position.toArray()),gap=(a,b)=>Math.hypot(...a.map((v,i)=>v-b[i]));
 try{
 await p.goto('http://127.0.0.1:8766/garden/');await p.waitForSelector('body[data-garden-ready=true]');await p.locator('#enterButton').click();await p.locator('#lookoutButton').click();assert(await p.locator('#ziplineButton').isDisabled(),'Ride requires reaching the viewing deck');await p.locator('#viewLookout').click();await p.locator('[data-theme=day]').click();
 await p.locator('#ziplineButton').click();assert(await p.locator('#zipDialog').isVisible(),'Ride has a deliberate start and instant alternative');await p.screenshot({path:'output/playwright/zipline-ready.png'});await p.locator('#startZip').click();await p.waitForTimeout(800);await p.locator('#pauseZip').click();await p.waitForTimeout(150);const paused=await pos();await p.waitForTimeout(400);assert(gap(paused,await pos())<.001,'Pause freezes the rider on the cable');await p.screenshot({path:'output/playwright/zipline-launch.png'});
 const beforeYaw=await p.evaluate(()=>gardenInspect.camera.rotation.y);await p.mouse.move(850,450);await p.mouse.down();await p.mouse.move(950,450,{steps:8});await p.mouse.up();await p.waitForTimeout(200);assert(Math.abs(await p.evaluate(()=>gardenInspect.camera.rotation.y)-beforeYaw)>.1,'Paused riders can still look around');await p.keyboard.down('w');await p.waitForTimeout(300);await p.keyboard.up('w');assert(gap(paused,await pos())<.001,'Walking input cannot detach a paused rider');
 await p.locator('#pauseZip').click();await p.waitForTimeout(4200);await p.locator('#clearZip').click();const a=await pos();await p.waitForTimeout(900);assert(gap(a,await pos())>2,'Glide continues in clear view');assert(!await p.locator('#quietWalk').isVisible(),'Walking pad stays hidden during the ride');await p.screenshot({path:'output/playwright/zipline-glide.png'});await p.keyboard.press('Escape');assert(await p.locator('#pauseZip').textContent()==='Resume ride','Escape restores ride controls and pauses');await p.locator('#pauseZip').click();await p.waitForFunction(()=>!document.body.classList.contains('zip-riding'),null,{timeout:25000});
 const landing=await pos();assert(Math.hypot(landing[0]-3,landing[2]-28)<.01,'Complete ride reaches the wooden landing');assert(await p.locator('#returnZipTower').isVisible(),'Landing offers a return to the tower');await p.screenshot({path:'output/playwright/zipline-landing.png'});await p.keyboard.down('w');await p.waitForTimeout(1800);await p.keyboard.up('w');assert(gap(landing,await pos())>1,'Visitors can walk from the landing back into the garden');
 await p.locator('#returnZipTower').click();await p.locator('#ziplineButton').click();await p.locator('#startZip').click();await p.waitForTimeout(1200);await p.locator('#helpButton').click();const helpPos=await pos();await p.waitForTimeout(500);assert(gap(helpPos,await pos())<.001,'FAQs pause the ride');await p.locator('#doneHelp').click();await p.locator('#returnZip').click();assert(await p.locator('#ziplineButton').isEnabled()&&!await p.locator('#zipRidePanel').isVisible(),'Returning exits the ride at the tower deck');
 await p.locator('#motionButton').click();await p.locator('#ziplineButton').click();assert(await p.locator('#startZip').isDisabled(),'Still mode prevents animated launch');await p.locator('#visitZipLanding').click();assert(Math.hypot((await pos())[0]-3,(await pos())[2]-28)<.01,'Still mode can visit the landing instantly');
 assert(errors.length===0,`No runtime or shader errors: ${errors.join('; ')}`);return {checks};
 }finally{await context.close();}
}
