import test from 'node:test';
import assert from 'node:assert/strict';
import {route,groundHeight,canWalk,cleanWalkSave,places,ROUTE_LENGTH,breakJourney} from '../walk-route.mjs';
test('The complete guided loop is walkable, closed and has smooth bridge approaches',()=>{assert.ok(ROUTE_LENGTH>150);assert.ok(route.getPointAt(0).distanceTo(route.getPointAt(1))<.001);let previous;for(let i=0;i<=2000;i++){const p=route.getPointAt(i/2000);assert.equal(canWalk(p.x,p.z),true,`blocked route at ${i}`);const h=groundHeight(p.x,p.z);assert.ok(Number.isFinite(h));if(previous!==undefined)assert.ok(Math.abs(h-previous)<.075,`abrupt step at ${i}`);previous=h;}for(const p of places){const v=route.getPointAt(p.t);assert.equal(canWalk(v.x,v.z),true);}});
test('Free walking respects water, trunks and outer garden boundaries',()=>{assert.equal(canWalk(5,5),false);assert.equal(canWalk(5,-4),true);assert.equal(canWalk(0,30,[{x:0,z:30,r:.4}]),false);assert.equal(canWalk(40,0),false);assert.equal(canWalk(NaN,1),false);});
test('Walking preferences validate untrusted browser storage and retain the miniature save separately',()=>{assert.deepEqual(cleanWalkSave({theme:'invalid',pace:99,still:'yes',opened:[1,1,-1,99,3,'4']}),{season:'summer',natureVolume:1,footstepsVolume:1,weather:'clear',weatherAuto:false,theme:'sunset',pace:1.3,still:false,opened:[1,3]});assert.equal(cleanWalkSave(null).theme,'sunset');});

test('Sound balance preserves silence and validates older or invalid preferences',()=>{assert.equal(cleanWalkSave(null).natureVolume,1);assert.equal(cleanWalkSave({footstepsVolume:0}).footstepsVolume,0);assert.equal(cleanWalkSave({natureVolume:.6}).natureVolume,.6);assert.equal(cleanWalkSave({natureVolume:99}).natureVolume,1);assert.equal(cleanWalkSave({footstepsVolume:-1}).footstepsVolume,0);assert.equal(cleanWalkSave({natureVolume:'0',footstepsVolume:NaN}).footstepsVolume,1);assert.equal(cleanWalkSave({natureVolume:'0'}).natureVolume,1);});

test('Woodland, meadow and reading nook are on the extended walkable loop',()=>{assert.ok(ROUTE_LENGTH>270);for(const i of[6,7,8]){const p=route.getPointAt(places[i].t);assert.ok(p.x < -30);assert.equal(canWalk(p.x,p.z),true);}assert.equal(cleanWalkSave({season:'autumn',opened:[8]}).season,'autumn');assert.deepEqual(cleanWalkSave({opened:[8,99]}).opened,[8]);assert.equal(cleanWalkSave({season:'bad'}).season,'summer');});
test('Every two-minute break arrives at the woodland bench at the selected pace',()=>{for(const pace of[.8,1.3,1.8]){const trip=breakJourney(pace);assert.ok(Math.abs(((trip.start+trip.speed*trip.duration/ROUTE_LENGTH)%1)-places[4].t)<1e-9);assert.equal(trip.duration,120);}});
