from copy import deepcopy
from common import entry as E, source as S
from australian_common import DATA as NATIONAL
DATA = deepcopy(NATIONAL)
DATA.update({
'mca': E(
'''The Guardianship Act 1987 provides important guardianship and medical-consent routes. For a patient unable to consent to relevant medical or dental treatment, identify the statutory person responsible: an authorised guardian first, then an eligible spouse or partner, unpaid carer, or close relative or friend in the prescribed order. Next of kin is not automatically the correct person.

Treatment categories and objections matter. NCAT guidance distinguishes ordinary substitute-consent situations from special treatment and situations involving an objection. An enduring guardian’s welfare functions and an attorney’s financial functions also require separate document checks.''',
['Support the patient’s own decision and establish the precise treatment and capacity question.', 'Read the appointment and apply the person-responsible hierarchy, including eligibility and availability.', 'Check the treatment category and whether the patient objects; do not assume a representative can override that objection.', 'Seek the applicable NCAT or clinical/legal route where consent cannot lawfully be obtained through the ordinary hierarchy.'],
'NCAT’s Guardianship Division can deal with relevant appointments, reviews and treatment-consent applications. Explain the person’s participation and access to advice. A guardianship order must be read for its specific functions; it is not a general transfer of all decisions.',
'A daughter who manages bills offers consent for a procedure, while the patient objects and an appointed guardian has a medical-consent function.',
'Check the patient’s decision-making ability and objection, then the guardian’s actual authority and the treatment category. The daughter’s financial help does not settle the consent route. Obtain the appropriate specialist or NCAT advice rather than collecting whichever signature is easiest.',
'Treating next of kin as the automatic decision-maker or ignoring an objection because a relative agrees.',
[S('NCAT person responsible guidance', 'https://ncat.nsw.gov.au/publications-and-resources/fact-sheets/person-responsible-fact-sheet.html', 'policy'), S('Guardianship Act 1987', 'https://legislation.nsw.gov.au/view/html/inforce/current/act-1987-257'), S('NCAT guardianship jurisdiction', 'https://ncat.nsw.gov.au/case-types/guardianship.html', 'policy')]),
'dols': E(
'''For NDIS services, the Commonwealth behaviour-support and restrictive-practices rules operate alongside NSW authorisation requirements. A behaviour support plan, the state authorisation process and provider reporting obligations are separate parts of the framework. Lodging a plan with the NDIS Commission is not itself NSW authorisation.

NSW DCJ publishes the Restrictive Practices Authorisation policy and procedural guide. Healthcare, aged care and mental-health settings have different rules. A person-responsible medical-consent role does not automatically authorise environmental restraint or confinement in a disability service.''',
['Identify the practice, its purpose and whether it is a regulated restrictive practice in the actual setting.', 'Check the NSW authorisation process alongside the NDIS plan, provider and reporting requirements.', 'Verify consent or representative authority where relevant without treating it as a substitute for authorisation.', 'Record alternatives, conditions, monitoring, review and the strategy for reducing the practice.'],
'The person should have accessible information, support to express objections and the applicable provider, NDIS Commission or legal review route. Unauthorised use may trigger incident-reporting duties. Check current rules for timing and recipients rather than waiting for routine plan review.',
'An NDIS provider locks kitchen cupboards and says the uploaded behaviour plan is all the permission it needs.',
'Identify the restriction’s purpose and effect, examine the NSW authorisation requirements and check the person’s participation. Consider less restrictive access and support. Resolve missing approvals and any incident duties with the responsible practitioners; an uploaded plan does not resolve them.',
'Equating a behaviour support plan with all state approvals, or applying disability-service rules to every hospital or care setting.',
[S('NSW restrictive-practices authorisation policy', 'https://dcj.nsw.gov.au/service-providers/deliver-disability-services/restrictive-practices-authorisation-portal/policy.html', 'policy'), S('NDIS implementing-provider rules', 'https://www.ndiscommission.gov.au/rules-and-standards/behaviour-support-and-restrictive-practices/rules-implementing-providers', 'policy')]),
'mha': E(
'''The Mental Health Act 2007 distinguishes mentally ill and mentally disordered persons and provides different assessment, detention and treatment routes. For the mentally ill person definition, mental illness must connect to the need for care, treatment or control to protect the person or others from serious harm. The mentally disordered route has its own serious-physical-harm test and limits.

Check the Act’s less restrictive care requirements and the exact role of authorised medical officers, the Mental Health Review Tribunal and other authorised persons. Community treatment orders and inpatient detention are different measures. A social-work qualification alone does not confer every transport or detention power.''',
['Identify the proposed route and connect the actual evidence to its criteria.', 'Consider whether appropriate care is reasonably available through a less restrictive alternative.', 'Verify the assessment, certification, notice and tribunal requirements for that status.', 'Separate psychiatric treatment powers from consent to unrelated medical treatment and from the discharge support plan.'],
'Explain rights information, the applicable carer or designated-person arrangements, legal representation and Mental Health Review Tribunal review. Read the person’s actual documents and the current statutory time limits rather than treating every admission as a fixed period that must be completed.',
'A person declines admission but accepts a crisis-team visit and support from a friend. Staff describe the refusal as sufficient reason for detention.',
'Assess the harm evidence and whether the offered alternative is suitable and available. Ask the authorised clinician to apply the relevant criteria and record the reasoning. The refusal is one fact to understand, not a complete statutory assessment.',
'Confusing mentally ill and mentally disordered routes or treating a diagnosis and refusal as the whole detention test.',
[S('Mental Health Act 2007, current text', 'https://legislation.nsw.gov.au/view/html/inforce/current/act-2007-008'), S('Mental Health Act 2007, current PDF', 'https://legislation.nsw.gov.au/view/pdf/inforce/current/act-2007-008')]),
'safeguarding': E(
'''The Ageing and Disability Commissioner Act 2019 and the NSW Ageing and Disability Commission (ADC) provide a route for concerns about abuse, neglect or exploitation of older people and adults with disability. The ADC considers reports, advice, referrals and investigation within its remit, with consent and statutory exceptions relevant to investigation.

Concerns about an NDIS provider, an aged-care service, a health service, crime or family violence may require a different or additional route. Identify the setting and relationship; one report to the ADC does not necessarily discharge another organisation’s incident-reporting duties.''',
['Arrange a safe conversation and identify immediate danger, dependency and the adult’s desired outcomes.', 'Consider an ADC report where there are reasonable grounds for the relevant concern.', 'Identify any police, NDIS Commission, aged-care or provider reporting requirement separately.', 'Record consent and information-sharing reasoning, practical safety support and who will follow up.'],
'The ADC can explain its response and refer matters beyond its scope. Support the adult to use the relevant complaint or legal route and preserve participation where they fear retaliation. A referral is not permission to impose a placement or take over finances.',
'An older person reports that a relative takes their money, while a provider separately fails to deliver agreed meals.',
'Map the financial exploitation and the service failure as distinct concerns. Arrange immediate food access and safe contact, consider ADC and any police response, and pursue the provider or regulator pathway for missed care. Check who has accepted each action.',
'Assuming that every adult-safety concern belongs to one agency or that reporting creates substitute decision-making powers.',
[S('ADC response to reports', 'https://ageingdisabilitycommission.nsw.gov.au/about-us/reporting/our-response-to-reports.html', 'policy'), S('Ageing and Disability Commissioner Act 2019', 'https://legislation.nsw.gov.au/view/html/inforce/current/act-2019-007')]),
'children': E(
'''The Children and Young Persons (Care and Protection) Act 1998 provides the child-protection framework. Mandatory-reporting obligations depend on the professional role and circumstances, including reasonable grounds to suspect a child is at risk of significant harm. The statutory mandatory duty for a child and the ability to report concerns about a young person must be distinguished.

DCJ’s Mandatory Reporter Guide supports decisions about the response but does not replace the Act or immediate safety action. Child-protection reporting, police reporting and an organisation’s incident or reportable-conduct procedures can be separate duties.''',
['Check the child’s age, your role and the applicable reporting threshold under the Act.', 'Use the current DCJ guidance and appropriate Child Protection Helpline or other reporting route.', 'Record the concern, evidence, child’s account and report without waiting to prove the allegation.', 'Plan family support and cultural participation, including relevant Aboriginal placement and participation requirements where engaged.'],
'Explain the role of DCJ, any court process and how the child and family can obtain support or legal advice. A voluntary support referral does not replace a mandatory report when its conditions are met. Preserve safe communication and reporter confidentiality under the applicable rules.',
'A worker hears a child describe violence at home and is told that a referral to a family-support charity is sufficient.',
'Assess immediate safety and the significant-harm concern, check the reporting duty and use the appropriate DCJ or police route. Family support may be valuable alongside that action, but it cannot be used to avoid an applicable statutory report.',
'Treating a support referral or an internal incident entry as the required child-protection report.',
[S('DCJ mandatory reporters', 'https://dcj.nsw.gov.au/children-and-families/protecting-our-kids/mandatory-reporters/who-are-mandatory-reporters.html', 'policy'), S('Children and Young Persons (Care and Protection) Act 1998', 'https://legislation.nsw.gov.au/view/html/inforce/current/act-1998-157')]),
'rights': E(
'''The Anti-Discrimination Act 1977 and relevant Commonwealth discrimination laws form part of the NSW rights map. For records, distinguish the Privacy and Personal Information Protection Act 1998 from the Health Records and Information Privacy Act 2002 (HRIP), as well as any Commonwealth privacy obligations applying to the organisation.

The HRIP health-privacy principles concern collection, storage, access, use and disclosure within their statutory scope. Identify whether the organisation is a public agency, health-service provider or another covered entity. A service’s privacy policy should explain its duties, not be treated as a separate permission to disregard them.''',
['Identify the state or Commonwealth duty relevant to access, discrimination or the proposed intervention.', 'Arrange accessible communication and culturally safe participation chosen with the person.', 'Check the applicable information regime and lawful purpose before collection or disclosure.', 'Explain access, correction and complaint rights, including the appropriate Information and Privacy Commission route.'],
'NSW IPC guidance distinguishes consent and other legal bases for information handling. A broad consent form does not remove all privacy obligations. A discrimination complaint, a privacy complaint and review of a service decision require different pathways.',
'A provider proposes sending a complete health record to a housing worker because both organisations support the same client.',
'Clarify the housing decision, the relevant information and the applicable privacy framework. Seek or identify the appropriate legal basis, respect confidentiality limits and record what is shared. The shared client does not make unrestricted file exchange necessary.',
'Assuming that working with the same person creates unrestricted authority to share health records.',
[S('NSW health privacy principles', 'https://www.ipc.nsw.gov.au/resources/fact-sheet-health-privacy-principles-hpps', 'policy'), S('HRIP Act and scope', 'https://www.ipc.nsw.gov.au/privacy/nsw-privacy-laws/hrip', 'policy'), S('Anti-Discrimination Act 1977', 'https://legislation.nsw.gov.au/view/html/inforce/current/act-1977-048')]),
})
