from copy import deepcopy
from common import entry as E, source as S
from australian_common import DATA as NATIONAL
DATA = deepcopy(NATIONAL)
DATA.update({
'mca': E(
'''The Medical Treatment Planning and Decisions Act 2016 governs important medical-consent and advance-care-directive questions. The Guardianship and Administration Act 2019 provides a separate framework for guardianship, administration and supported appointments. Specify whether the decision concerns treatment, personal matters or finances. Medical decision-making capacity concerns understanding the relevant information and effects, retaining it for the decision, considering it when choosing, and conveying the choice and related views or needs by any workable means. Provide practical support first; an apparently unwise choice does not establish incapacity.

An advance care directive can include an instructional directive and a values directive, with different effects. Where the person cannot make the treatment decision, identify the lawful medical treatment decision maker. Their task concerns the decision the person would have made, informed by relevant preferences and values, rather than simply the representative’s preferred outcome.''',
['Support the person to make the specific decision and assess the relevant decision-making ability.', 'Check for a valid, applicable instructional directive and distinguish it from a values statement.', 'Identify the medical treatment decision maker under the applicable appointment or hierarchy.', 'For a separate personal or financial issue, verify the scope of the relevant guardian, administrator or other arrangement.'],
'The Office of the Public Advocate (OPA) explains healthcare decision-making and routes where no appropriate decision maker is available. VCAT has relevant guardianship and other statutory functions. Disputed authority or treatment requires the route applicable to that decision, not a general family vote.',
'A person’s advance directive refuses a particular treatment, but a relative asks the team to ignore it because they believe treatment would help.',
'Check validity, applicability and whether the statement is an instructional or values directive. Involve the responsible clinician and obtain advice where the position is disputed. Do not substitute the relative’s preference for the legal effect of the document or the person’s own decision.',
'Treating an instructional directive as merely optional, or assuming financial administration includes medical consent.',
[S('OPA healthcare rights', 'https://www.publicadvocate.vic.gov.au/your-rights/your-healthcare', 'policy'), S('Interpreting an instructional directive', 'https://www.publicadvocate.vic.gov.au/medical-treatment/patient-consent/interpreting-an-instructional-directive', 'policy'), S('Medical Treatment Planning and Decisions Act 2016', 'https://www.legislation.vic.gov.au/in-force/acts/medical-treatment-planning-and-decisions-act-2016'), S('Guardianship and Administration Act 2019', 'https://www.legislation.vic.gov.au/in-force/acts/guardianship-and-administration-act-2019')]),
'dols': E(
'''The Disability Act 2006 and Victorian Senior Practitioner arrangements operate alongside the NDIS restrictive-practices framework where applicable. Authorised Program Officers, the Senior Practitioner, behaviour support practitioners and implementing providers have different responsibilities. A plan is not proof that every necessary authorisation or approval exists.

The Senior Practitioner publishes directions and prohibitions, including a permanent-prohibition notice dated September 2025. Check the current rules for the particular practice and cohort before considering an application. A prohibited practice is not made permissible by including it in a behaviour support plan.''',
['Identify the actual restriction, setting and whether the disability, mental-health or aged-care framework applies.', 'For the disability route, check the Authorised Program Officer and Senior Practitioner requirements and current prohibitions.', 'Check NDIS plan, authorisation and incident-reporting requirements separately where they apply.', 'Record participation, alternatives, conditions, review and the strategy for reducing the restriction.'],
'OPA, advocacy services and the relevant regulator can assist with concerns within their remits. The person needs a usable way to object and seek the applicable legal or administrative review. A guardian’s agreement does not remove the statutory restrictions on restraint.',
'A provider proposes a restraint copied from an old plan and assumes approval can be renewed without checking current directions.',
'Check whether the practice is now prohibited and whether the previous approval is relevant to the present circumstances. Assess alternatives and consult the responsible practitioner. Do not apply an obsolete approval to a new plan or bypass the Senior Practitioner’s requirements.',
'Treating historical approval or a lodged plan as permanent permission, including for a prohibited practice.',
[S('Victorian Senior Practitioner responsibilities', 'https://www.dffh.vic.gov.au/about-victorian-senior-practitioner', 'policy'), S('Current directions and prohibitions', 'https://www.dffh.vic.gov.au/victorian-senior-practitioners-directions-and-prohibitions', 'policy'), S('Disability Act 2006', 'https://www.legislation.vic.gov.au/in-force/acts/disability-act-2006'), S('NDIS implementing-provider rules', 'https://www.ndiscommission.gov.au/rules-and-standards/behaviour-support-and-restrictive-practices/rules-implementing-providers', 'policy')]),
'mha': E(
'''The Mental Health and Wellbeing Act 2022 replaced the 2014 Act. It prefers voluntary assessment and treatment and provides separate assessment orders, temporary treatment orders and Mental Health Tribunal treatment orders. Each stage has its own authorised decision-maker and requirements.

Compulsory treatment criteria include mental illness; immediate treatment needed to prevent serious deterioration in health or serious harm; that treatment being provided if the order is made; and no reasonably available less restrictive means. Evidence that a service is actually available matters. Assessment-order criteria should not be replaced with the treatment-order test.''',
['Identify the stage, authorised practitioner and exact statutory criteria.', 'Record the person’s preferences, available voluntary alternatives and why the proposed order is necessary.', 'Check advance statements of preferences, nominated support persons and supported decision-making requirements.', 'Separate treatment consent, any statutory treatment authority and additional safeguards for particular interventions.'],
'Explain the statement of rights, non-legal advocacy, second psychiatric opinion and Mental Health Tribunal routes. Current handbook guidance describes their application. A nominated support person assists participation; their role should not be treated as a general substitute-consent appointment.',
'A person is considered for a treatment order, but the proposed immediate treatment has not been arranged and a community alternative has not been explored.',
'Check all criteria, including that treatment will be provided and whether a less restrictive means is reasonably available. Obtain the person’s preferences and supports. The existence of illness and concern about deterioration alone does not explain the whole order decision.',
'Using the assessment and treatment criteria interchangeably or treating a support person as the treatment decision-maker.',
[S('Mental Health and Wellbeing Act 2022', 'https://www.legislation.vic.gov.au/in-force/acts/mental-health-and-wellbeing-act-2022'), S('Compulsory assessment and treatment handbook', 'https://www.health.vic.gov.au/mental-health-and-wellbeing-act-handbook/compulsory-assessment-and-treament', 'policy'), S('Treatment-order criteria and process', 'https://www.health.vic.gov.au/mental-health-and-wellbeing-act-handbook/treatments-and-interventions/treatment-orders', 'policy')]),
'safeguarding': E(
'''Adult concerns may require family-violence services, police, OPA, disability safeguards, aged-care oversight or a provider complaint. Identify the relationship and service setting before selecting a route. The Family Violence Protection Act 2008 is relevant to violence and abuse within its defined relationships; not every adult concern is governed by that framework.

The Orange Door provides access to family-violence and family-support services. NDIS and aged-care providers have their own incident and regulatory obligations. A referral for support, a reportable incident and an application for a protective order are different actions.''',
['Hear the adult safely and identify immediate danger, coercion and practical dependence.', 'Identify whether the concern involves family violence, a disability or aged-care provider, another service or crime.', 'Use the relevant specialist, police and regulatory routes, checking any mandatory reporting duty.', 'Plan safe contact, practical support and follow-up without assuming that a referral authorises coercive action.'],
'Explain the appropriate complaint, advocacy or court route for the issue. OPA can provide information about decision-making and rights within its remit. Keep the adult’s wishes and the legal authority for any intervention visible, including where agencies disagree.',
'An adult with disability reports financial control by a partner and an unrelated failure by a support provider to deliver personal care.',
'Assess the family-violence concern and provider failure separately while coordinating safety. Consider the specialist family-violence route and the appropriate provider or NDIS response. Arrange continuity of care and safe contact rather than assuming one agency will handle both matters.',
'Treating all adult safeguarding as one statutory process or assuming a guardianship referral resolves family violence.',
[S('Family Violence Protection Act 2008', 'https://www.legislation.vic.gov.au/in-force/acts/family-violence-protection-act-2008'), S('The Orange Door', 'https://www.orangedoor.vic.gov.au/', 'policy'), S('Office of the Public Advocate', 'https://www.publicadvocate.vic.gov.au/', 'policy')]),
'children': E(
'''The Children, Youth and Families Act 2005 distinguishes protection grounds and mandatory reporting. The mandatory-reporter categories depend on the role: do not assume every person called a social worker is included solely by title. A social worker may fall within a listed role, such as school counselling or out-of-home care work.

DFFH guidance requires listed reporters who form the relevant reasonable belief in their work to report protection concerns involving physical injury or sexual abuse. Other forms of significant harm may also be reported. The child’s harm and parental protection must be considered; the statutory reporting duty is not identical to every possible wellbeing concern.''',
['Check the actual professional or employment category and the applicable reporting duty.', 'Report to Child Protection as soon as practicable where the duty is engaged, including new grounds arising later.', 'Consider a support referral to The Orange Door where appropriate, without substituting it for a required protection report.', 'Check separate police and organisational duties, and plan child participation, cultural support and continuity.'],
'Explain the Child Protection process and the child’s and family’s access to support or legal advice. DFFH guidance distinguishes reporting routes from family-support referrals. Advice within an organisation should not delay an applicable personal reporting obligation.',
'A school counsellor receives a disclosure of physical harm, while a colleague says the family should first be referred for voluntary parenting support.',
'Check the reasonable-belief and protection conditions and make the required report if met. Assess immediate safety and follow any separate police duty. Parenting support can run alongside the protection response; it does not replace it.',
'Assuming all social-work job titles create the same reporting duty, or confusing voluntary support with a mandatory report.',
[S('DFFH mandatory reporting, updated August 2026', 'https://providers.dffh.vic.gov.au/mandatory-reporting', 'policy'), S('Children, Youth and Families Act 2005', 'https://www.legislation.vic.gov.au/in-force/acts/children-youth-and-families-act-2005')]),
'rights': E(
'''The Charter of Human Rights and Responsibilities Act 2006 requires covered public authorities to act compatibly with Charter rights and give proper consideration to relevant rights, subject to statutory exceptions. Identify whether the provider is a public authority for the function involved. A Charter statement should explain the affected rights and reasoning, not simply declare compliance.

The Equal Opportunity Act 2010, Health Records Act 2001 and Privacy and Data Protection Act 2014 have different scopes. Commonwealth law may also apply. Determine the organisation and information involved before selecting a privacy or discrimination pathway.''',
['Identify the relevant Charter rights and whether the decision-maker is a covered public authority.', 'Consider the actual impact, alternatives and any lawful basis for limiting a right.', 'Arrange accessible and culturally safe participation and address applicable equality obligations.', 'Check the relevant privacy regime and explain access, correction, complaints and review.'],
'The Victorian Equal Opportunity and Human Rights Commission explains Charter duties and discrimination. Privacy and health complaints use their respective bodies and statutory routes. Obtain advice about the remedy for an alleged Charter breach rather than promising that every concern has a standalone Charter claim.',
'A public service restricts all family visits for administrative convenience without considering a resident’s cultural and family relationships.',
'Identify the rights affected, the purpose of the restriction and realistic alternatives. Hear the resident and supporters they choose, consider the applicable legal duties and record the reasoning. Review the blanket policy’s effect on the individual rather than relying only on its general wording.',
'Assuming every private provider has identical Charter duties or that naming rights establishes proper consideration.',
[S('Charter responsibilities of public authorities', 'https://www.humanrights.vic.gov.au/for-public-sector/charter-responsibilities/charter-and-the-government/', 'policy'), S('Charter of Human Rights and Responsibilities Act 2006', 'https://www.legislation.vic.gov.au/in-force/acts/charter-human-rights-and-responsibilities-act-2006'), S('Health Records Act 2001', 'https://www.legislation.vic.gov.au/in-force/acts/health-records-act-2001')]),
})

DATA['mca']['sources'].append(S('Patient capacity to consent', 'https://www.publicadvocate.vic.gov.au/medical-treatment/patient-consent/patient-capacity-to-consent'))
