from common import entry as E, source as S
DATA = {
'foundations': E(
'''The Ontario College of Social Workers and Social Service Workers (OCSWSSW) regulates two professions with distinct scopes. Its Code of Ethics and Standards of Practice address relationships, competence, responsibilities, records, confidentiality, fees, communication and boundaries. Use the current standards alongside the legislation applying to the task.

Registration does not make every registrant a designated capacity assessor or confer every controlled-act or statutory power. Establish the role, competence and additional requirements before undertaking specialist work. Identify whether the employer is a health-information custodian, a public body or another organisation because that affects records and disclosure duties.''',
['Confirm registration, professional scope and any additional authority required.', 'Explain the service, purpose of assessment, informed consent and confidentiality limits.', 'Use supervision to examine bias, cultural safety and the effect of poverty or institutional barriers.', 'Connect continuing competence to changes in practice and the current College programme.'],
'A complaint to the College concerns professional conduct or practice. A funding appeal, health-service complaint or privacy complaint has a different route. Clarify which decision the person wants changed and who can address it.',
'A manager asks a registered social worker to complete a statutory assessment requiring a particular assessor designation.',
'Check the legal requirements and the worker’s actual designation, competence and scope. Arrange an appropriately authorised assessor if needed. Continue gathering relevant social evidence without representing that work as the statutory determination.',
'Treating College registration as proof of every specialist assessment qualification.',
[S('OCSWSSW Code and Standards', 'https://www.ocswssw.org/sop/', 'professional-standards'), S('Social Work and Social Service Work Act 1998', 'https://www.ontario.ca/laws/statute/98s31')]),
'care-support': E(
'''Ontario Health atHome coordinates important home-care and long-term-care placement functions. Distinguish home-care eligibility, the amount or type of service, placement eligibility and a provider’s delivery. Income support, developmental services, housing and privately arranged care have separate rules.

Ontario Health atHome identifies appealable matters including eligibility, service amounts, exclusion or discontinuation of services and long-term-care admission eligibility. Discussion with a coordinator, management review and an external appeal are not the same step. Obtain the decision and the appropriate route in writing.''',
['Identify the actual programme and responsible assessment or funding body.', 'Document daily needs, personal goals, informal support and the effect of service gaps.', 'Separate the eligibility decision, care-plan allocation, any charges and the start of provision.', 'Request reasons and track the relevant complaint, formal review or appeal for the disputed decision.'],
'Ontario Health atHome’s feedback process begins with the care coordinator and a patient-services manager and includes formal review for unresolved issues. Certain decisions may be appealed to the Health Services Appeal and Review Board. Check the notice and time limits; a provider-quality complaint is a separate issue.',
'An adult’s home-care visits are reduced although their mobility has worsened. The family is told only to complain to the visiting agency.',
'Establish who reduced the allocation and obtain the reassessment and reasons. Address immediate safety with the coordinator and use the relevant service-decision review or appeal. Pursue a provider complaint separately if the agency also failed to deliver the authorised visits.',
'Confusing a complaint about a worker with an appeal against the amount of funded care.',
[S('Ontario Health atHome feedback and appeals', 'https://www.ontariohealthathome.ca/contact/patient-experience-and-feedback/', 'policy'), S('Connecting Care Act 2019', 'https://www.ontario.ca/laws/statute/19c05c')]),
'mca': E(
'''The Health Care Consent Act 1996 (HCCA) distinguishes treatment, admission to a care facility and personal-assistance decisions. Its capacity test asks whether the person understands relevant information and appreciates reasonably foreseeable consequences of deciding or not deciding. The Substitute Decisions Act 1992 separately addresses property and personal-care arrangements.

For HCCA substitute consent, apply the statutory hierarchy and eligibility requirements. Applicable prior capable wishes matter; where no applicable wish governs, the statutory best-interests framework applies. A power of attorney must be checked for scope and operation rather than assumed to cover every decision.''',
['Specify the decision and identify which Act and decision-maker apply.', 'Support understanding and assess the relevant understanding-and-appreciation abilities.', 'Check the substitute hierarchy, eligibility and any appointment before seeking a decision.', 'Identify applicable prior capable wishes and use the statutory decision standard where substitute consent is required.'],
'The Consent and Capacity Board has review and application functions under the HCCA and other legislation. Rights advice and procedural safeguards depend on the decision and setting. An SDA property assessment should not be substituted for a treating practitioner’s HCCA determination.',
'A hospital patient understands a proposed treatment but has a property guardian. Staff ask the guardian to consent without assessing treatment capacity.',
'Assess the patient’s ability for the treatment decision and provide support. Read the guardian’s powers and identify the correct HCCA route only if substitute consent is needed. Financial guardianship is not evidence that the patient cannot consent to treatment.',
'Equating financial incapacity with treatment incapacity or ignoring applicable prior capable wishes.',
[S('Health Care Consent Act 1996', 'https://www.ontario.ca/laws/statute/96h02'), S('Substitute Decisions Act 1992', 'https://www.ontario.ca/laws/statute/92s30')]),
'dols': E(
'''Admission to a care facility, consent to treatment and authority to restrain or confine are distinct questions. The HCCA, Mental Health Act and setting-specific legislation such as the Fixing Long-Term Care Act 2021 may be relevant. Read the provision and its commencement note: an enacted future amendment is not an operative confinement power.

Long-term-care restraint requirements and mental-health detention procedures should not be treated as one system. A substitute’s agreement to admission does not by itself explain every locked-door arrangement or restraint used after admission.''',
['Identify the actual restriction, setting, legal status and the person’s wishes.', 'Separate admission consent from the specific authority for restraint or detention.', 'Check the current setting-specific conditions, documentation, monitoring and any emergency exception.', 'Arrange less restrictive support, rights information and the relevant Board, court or complaints route.'],
'The person’s challenge route depends on the measure: a Consent and Capacity Board issue, a mental-health detention review or a long-term-care complaint may address different questions. Obtain advice about disputed confinement and preserve the person’s access to representation.',
'A long-term-care home says a daughter’s admission consent also permits a standing order preventing her father from leaving.',
'Read the admission and representative documents, assess the father’s wishes and the actual restriction, and identify the separate legal basis relied on. Check the current restraint and confinement provisions rather than assuming that admission consent answers the liberty question.',
'Treating consent to placement as blanket consent to confinement or relying on an uncommenced amendment.',
[S('Health Care Consent Act 1996', 'https://www.ontario.ca/laws/statute/96h02'), S('Fixing Long-Term Care Act 2021', 'https://www.ontario.ca/laws/statute/21f39'), S('Mental Health Act', 'https://www.ontario.ca/laws/statute/90m07')]),
'mha': E(
'''Ontario’s Mental Health Act provides assessment and involuntary-admission routes. A Form 1 permits a psychiatric assessment period of up to 72 hours when its criteria are met; it is not itself indefinite detention or automatic authority for every treatment. Subsequent involuntary status requires the applicable certification and safeguards.

The Act has different routes and criteria, including provisions relating to harm or serious impairment and specific deterioration circumstances. Apply the full relevant provision rather than reducing every route to a single danger test. Treatment consent remains a separate HCCA question.''',
['Identify the exact assessment or admission authority and the evidence supporting its criteria.', 'Record the start, expiry and required next decision for the actual legal status.', 'Arrange the applicable notices, rights advice and access to legal representation or Board review.', 'Assess treatment consent separately and coordinate a real discharge and follow-up plan.'],
'The Consent and Capacity Board reviews relevant involuntary-status and capacity matters. Rights advice is important when statutory notices or findings trigger it. A voluntary patient’s wish to leave requires the appropriate legal response; staff should not describe the person as detained without identifying a lawful basis.',
'A patient is held on Form 1 and a team assumes that this both permits medication without consent and authorises a longer stay.',
'Check the assessment period and whether a further lawful admission status is required. Apply HCCA consent separately to the proposed medication. Explain rights and arrange the relevant advice; neither the assessment form nor clinical preference resolves all three decisions.',
'Confusing an assessment hold, involuntary admission and authority to treat.',
[S('Ontario Mental Health Act', 'https://www.ontario.ca/laws/statute/90m07'), S('Ontario information for voluntary patients', 'https://www.ontario.ca/files/2024-05/moh-information-guide-voluntary-patients-en-2024-05-21.pdf', 'policy'), S('Health Care Consent Act 1996', 'https://www.ontario.ca/laws/statute/96h02')]),
'safeguarding': E(
'''Ontario has setting-specific adult-protection and reporting rules. The Fixing Long-Term Care Act 2021 and Retirement Homes Act 2010 contain reporting obligations for specified suspected harms, with different recipients and statutory exceptions. Community elder-abuse concerns require a different analysis; do not assume a single universal adult-reporting duty.

For long-term-care matters, identify the Ministry’s reporting route; retirement-home matters involve the Retirement Homes Regulatory Authority (RHRA). Police, healthcare, the Public Guardian and Trustee or other supports may also be relevant depending on the facts and authority involved.''',
['Identify the adult’s setting and the specific suspected abuse, neglect, unlawful conduct or financial misuse.', 'Apply the reporting threshold and recipient under the relevant Act, including any applicable exception.', 'Arrange immediate safety and safe contact while considering consent, coercion and information sharing.', 'Confirm receipt, responsibility and ongoing practical support rather than treating the report as the end of the response.'],
'Explain the relevant Ministry, RHRA, police or service complaint route. A reporting obligation does not itself authorise a worker to take over the adult’s finances or accommodation. Capacity and representative-authority questions require their own framework.',
'A worker hears about financial misuse affecting a retirement-home resident and is told to report only to the home’s manager.',
'Check the statutory reporting duty and RHRA route; internal reporting may not satisfy it. Address immediate access to funds and support, record the adult’s account and consider any separate police or representative concern.',
'Using one adult-safeguarding process for community, retirement-home and long-term-care settings.',
[S('Ontario elder-abuse information', 'https://www.ontario.ca/page/information-about-elder-abuse', 'policy'), S('Retirement Homes Act 2010', 'https://www.ontario.ca/laws/statute/10r11'), S('Fixing Long-Term Care Act 2021', 'https://www.ontario.ca/laws/statute/21f39')]),
'children': E(
'''The Child, Youth and Family Services Act 2017 (CYFSA) includes a direct and ongoing duty to report specified protection concerns to a children’s aid society where there are reasonable grounds to suspect them. A person with the duty must report directly rather than rely on a manager or colleague.

The mandatory duty in this provision does not apply in the same way to 16- and 17-year-olds, although concerns about them may be reported and services may be available. Age and the actual statutory ground matter. Indigenous child and family service jurisdiction and applicable community laws also need checking where relevant.''',
['Identify the child’s age, concern and reasonable grounds under the CYFSA.', 'Make the required direct report to the appropriate society and further reports when new grounds arise.', 'Record the child’s words and immediate safety needs without conducting an unnecessary parallel investigation.', 'Coordinate family support and participation, identifying any applicable Indigenous service authority and legal framework.'],
'Explain the society’s role, support and applicable court or review processes. Confidentiality has statutory limits where reporting is required. A report about an older teenager should not be dismissed simply because the same mandatory provision does not apply.',
'A worker raises a new concern about a 12-year-old and a manager says an earlier report by another worker covers it.',
'Assess the new reasonable grounds and make the required direct report. Record what is new, the child’s account and immediate safety arrangements. An earlier report does not remove the ongoing personal duty.',
'Delegating the report to a manager or applying the under-16 mandatory rule without checking the young person’s age.',
[S('CYFSA reporting guidance', 'https://files.ontario.ca/pdf-3/mccss-report-child-abuse-and-neglect-en-2022-03-31.pdf', 'policy'), S('Child, Youth and Family Services Act 2017', 'https://www.ontario.ca/laws/statute/17c14')]),
'rights': E(
'''The Ontario Human Rights Code protects against discrimination in covered areas and requires accommodation within the applicable legal framework. The Canadian Charter has its own scope concerning government action. Do not assume the same rights mechanism applies to every private and public service.

The Personal Health Information Protection Act 2004 (PHIPA) applies according to the role of the custodian, agent and information. Other organisations may be governed by different privacy laws. College confidentiality and recording standards operate alongside those laws, not in place of them.''',
['Identify the service decision, relevant protected ground and accommodation required.', 'Check whether PHIPA or another privacy regime governs the organisation and proposed disclosure.', 'Separate consent to service, consent to treatment and consent or other authority for information sharing.', 'Record evidence and disagreement and explain access, correction, privacy complaints and the relevant rights remedy.'],
'The Information and Privacy Commissioner of Ontario addresses privacy matters within its jurisdiction; the Human Rights Tribunal addresses applicable Code claims. A College complaint has a different purpose. Help the person seek the remedy relevant to the disputed act and obtain timely advice.',
'A social worker in a community organisation assumes they can share a complete file using a hospital’s implied-consent practice.',
'Identify the organisation’s legal status, purpose of disclosure and applicable law. Do not import the hospital’s framework without checking. Obtain or establish the proper basis, limit the disclosure and explain the person’s choices and complaint route.',
'Assuming every social worker is operating under the same health-information consent rules.',
[S('Personal Health Information Protection Act 2004', 'https://www.ontario.ca/laws/statute/04p03'), S('Ontario Human Rights Code', 'https://www.ontario.ca/laws/statute/90h19'), S('OCSWSSW legislation and confidentiality guidance', 'https://www.ocswssw.org/2018/10/03/practice-notes-whats-legislation-got-to-do-with-it/', 'professional-standards')]),
}
