from common import entry as E, source as S
DATA = {
'foundations': E(
'''The British Columbia College of Social Workers (BCCSW) Code of Ethics and Standards of Practice and the Social Workers Act provide the professional framework. Check the registration category, scope and any applicable statutory exemption or special role; a job title alone does not explain a practitioner’s regulatory position.

Health authorities, Community Living BC (CLBC), child and family services, Indigenous authorities and community organisations have different remits. Identify the organisation exercising the function and the law governing it. Cultural safety includes attention to Indigenous self-determination, racism and the person’s chosen community relationships.''',
['Confirm the practitioner’s role, regulatory position and any specific statutory designation.', 'Explain the purpose of involvement, participation and confidentiality limits.', 'Map the responsible health, community, child-service or Indigenous authority rather than treating all services as one system.', 'Use supervision and continuing learning to test evidence, bias and the practical effect of decisions.'],
'Distinguish a BCCSW professional complaint from a health-authority, service, privacy or statutory decision review. Help the person identify which body can address the action or remedy in question.',
'A worker assumes that employment by a health authority automatically gives them the powers of a designated adult-protection investigator.',
'Check the organisation’s designation and the worker’s actual role, authority and procedure. Gather relevant social evidence within scope and arrange the appropriate designated-agency response. Employment and statutory investigative authority should not be conflated.',
'Assuming every social-work role has identical registration requirements or investigative powers.',
[S('BCCSW Standards and Scope of Practice', 'https://bccsw.ca/for-registrants/standards-scope-of-practice/', 'professional-standards'), S('Social Workers Act', 'https://www.bclaws.gov.bc.ca/civix/document/id/complete/statreg/08031_01')]),
'care-support': E(
'''Publicly subsidised home and community care involves health-authority assessment, general eligibility and service-specific criteria. Provincial guidance addresses status, residence, age and health-related need, with exceptions to some general conditions. Do not convert a general criterion into an absolute exclusion without checking those exceptions.

Home support, long-term care, assisted living, CLBC supports and income assistance are different programmes. Needs assessment, access priority, client contribution and actual provision must be distinguished. The responsible office should explain which programme and policy support the decision.''',
['Contact the appropriate health-authority home and community care service for eligibility and needs assessment.', 'Check general and service-specific criteria, including any relevant exception.', 'Record assessed needs, family willingness, priority, costs and when support will actually begin.', 'Obtain reasons and the applicable health-authority review or complaint process if access or service levels are disputed.'],
'Provincial guidance distinguishes complaints about care from appeals of home and community care service decisions. Use the current health-authority process and decision notice. A provider complaint will not necessarily review a funding or eligibility decision.',
'A recently arrived older adult is told that a general residence requirement means no assessment or alternative support can be considered.',
'Check the published exceptions and the person’s actual health needs and circumstances. Identify any other relevant service while the eligibility question is resolved. Record reasons, interim support and the route for challenging the decision.',
'Applying general eligibility criteria without checking exceptions or treating an assessment as guaranteed service delivery.',
[S('Home and community care eligibility', 'https://www2.gov.bc.ca/gov/content/health/accessing-health-care/home-community-care/are-you-eligible', 'policy'), S('Arranging care and assessment', 'https://www2.gov.bc.ca/gov/content/health/accessing-health-care/home-community-care/how-to-arrange-for-care', 'policy'), S('Home and community care concerns and complaints', 'https://www2.gov.bc.ca/gov/content/health/accessing-health-care/home-community-care/concerns-and-complaints', 'policy')]),
'mca': E(
'''The Health Care (Consent) and Care Facility (Admission) Act has separate health-care and facility-admission provisions. The Representation Agreement Act and Patients Property Act provide other forms of authority. Identify the decision and the relevant document before deciding which route applies. For healthcare, the provider assesses whether the adult understands the relevant treatment information and its application to their own situation. Adapt communication to the adult’s abilities; a communication difference alone does not establish incapability.

Where temporary substitute consent for healthcare is needed, the healthcare provider selects the first available qualified person in the statutory list. The person’s prior capable instructions or wishes and the Act’s decision standard matter. An available relative is not automatically entitled to displace an authorised representative or another person with priority.''',
['Support the adult’s own decision and apply the relevant statutory incapability test.', 'Check any advance directive, representation agreement or committee order and its scope.', 'Where the temporary substitute route applies, use the statutory priority and qualification requirements.', 'Separate healthcare consent from admission and from personal or financial decisions under another framework.'],
'The Public Guardian and Trustee has relevant functions when a suitable substitute is unavailable or authority is disputed. Court or other statutory review may be needed depending on the issue. Explain the specific route and preserve the adult’s participation.',
'A friend offers to consent to treatment because they visit most often, although a valid representation agreement may appoint somebody else.',
'Assess the adult’s own ability and read the agreement. Determine the appropriate healthcare-consent route and priority before seeking consent. Frequent contact is useful evidence about wishes but does not by itself establish authority.',
'Using the temporary substitute list without checking an existing representative, or treating an agreement as unlimited authority.',
[S('Health Care (Consent) and Care Facility (Admission) Act', 'https://www.bclaws.gov.bc.ca/civix/document/id/complete/statreg/96181_01'), S('Representation Agreement Act', 'https://www.bclaws.gov.bc.ca/civix/document/id/complete/statreg/96405_01')]),
'dols': E(
'''Care-facility admission consent, treatment consent and authority for restraint or detention are distinct. The Health Care (Consent) and Care Facility (Admission) Act, facility licensing rules and Mental Health Act may apply in different circumstances. Read the actual measure and legal setting rather than treating admission as permission for every restriction.

Part 3 of the Adult Guardianship Act includes limited protective and emergency powers for designated agencies in defined circumstances. Those powers are not a general standing authority for a provider to confine an adult. The least intrusive response and the person’s wishes remain central to the assessment.''',
['Describe the restriction, who enforces it and the adult’s wishes or objections.', 'Identify the applicable facility, mental-health or designated-agency framework and the precise authority.', 'Check any order, emergency condition, monitoring duty and limit on duration or scope.', 'Explore alternatives and arrange the relevant independent support, complaint or legal review.'],
'Mental-health detention has review-panel and court routes; other disputed restrictions may require different legal advice or service-regulation responses. A healthcare substitute or a family member cannot be assumed to authorise every liberty restriction.',
'A care facility locks a resident’s door after an adult-protection referral and says the referral gives it authority to continue indefinitely.',
'Clarify whether any lawful emergency or court measure exists and its limits. Review the actual restriction and the adult’s wishes, arrange safer alternatives and obtain the appropriate legal or designated-agency advice. A referral itself confers no indefinite detention power.',
'Treating a protection referral or admission consent as authority for ongoing confinement.',
[S('Adult Guardianship Act', 'https://www.bclaws.gov.bc.ca/civix/document/id/complete/statreg/96006_01'), S('Health Care (Consent) and Care Facility (Admission) Act', 'https://www.bclaws.gov.bc.ca/civix/document/id/complete/statreg/96181_01'), S('Mental Health Act', 'https://www.bclaws.gov.bc.ca/civix/document/id/complete/statreg/96288_01')]),
'mha': E(
'''The Mental Health Act provides involuntary admission through medical certification and other defined routes. Section 22 addresses mental disorder requiring treatment, need for treatment in or through a designated facility, need for care, supervision and control to prevent substantial deterioration or protect the person or others, and inability to be suitably admitted voluntarily.

The statutory framework includes treatment authority for detained patients, which differs from ordinary substitute-consent healthcare. Do not import another province’s treatment-consent rule. The person’s status, required certificates and the particular treatment must all be checked.''',
['Identify the route and evidence for each applicable criterion, including voluntary alternatives.', 'Check certificates, dates, notices and renewal or review requirements.', 'Identify the legal basis for psychiatric treatment and distinguish unrelated healthcare decisions.', 'Arrange rights advice, access to a review panel or court process and the applicable second-opinion route.'],
'The Act includes rights advice, notice, review panels, court discharge applications and a second-medical-opinion provision. These mechanisms address different questions. Explain the route that fits the person’s concern rather than presenting a treatment complaint as identical to detention review.',
'A person is detained and a worker assumes the treatment-consent process must be identical to the one used in a neighbouring province.',
'Read the BC provisions governing the person’s actual status and proposed treatment. Explain the specific review and second-opinion rights, and assess unrelated physical healthcare under its own framework. Avoid substituting a familiar out-of-province process.',
'Reducing certification to immediate dangerousness alone or importing another province’s consent rules.',
[S('BC Mental Health Act, current consolidation', 'https://www.bclaws.gov.bc.ca/civix/document/id/complete/statreg/96288_01')]),
'safeguarding': E(
'''Part 3 of the Adult Guardianship Act concerns abuse, neglect or self-neglect where an adult cannot seek support and assistance because of the specified restraint, disability, illness, injury or decision-related conditions. Designated agencies must look into relevant reports. The statutory threshold and agency role should be stated explicitly.

Designated agencies include regional health bodies and, within defined remits, CLBC and Providence Health Care. The Public Guardian and Trustee has different functions. An adult need not already be a service user for a relevant concern to be considered.''',
['Identify the alleged harm and why the adult may be unable to seek assistance themselves.', 'Refer to the designated agency appropriate to the person and setting.', 'Arrange immediate safety and consider police or other statutory duties where needed.', 'Separate voluntary support, investigation, emergency action and a court-backed support-and-assistance plan.'],
'Preserve the adult’s participation and use the Act’s principles concerning autonomy and effective, least intrusive support. A designated-agency investigation is not the same as appointing a substitute decision-maker. Obtain advice where an imposed plan or emergency power is proposed.',
'A person understands that a family member is taking money but is physically prevented from leaving home or contacting services.',
'Consider the inability to seek assistance and the relevant designated-agency route rather than rejecting the concern because the person understands the abuse. Arrange safe communication, practical protection and any police response, with the adult’s wishes clearly recorded.',
'Treating decisional incapability as the only reason an adult may qualify for assistance.',
[S('PGT: protecting an adult from abuse or neglect', 'https://www.trustee.bc.ca/adults/protecting-vulnerable-adult-abuse-neglect-or-self-neglect', 'policy'), S('Adult Guardianship Act', 'https://www.bclaws.gov.bc.ca/civix/document/id/complete/statreg/96006_01'), S('Designated Agencies Regulation', 'https://www.bclaws.gov.bc.ca/civix/document/id/complete/statreg/11_19_2002')]),
'children': E(
'''The Child, Family and Community Service Act (CFCSA) defines a child as a person under 19 and creates a duty to report where its protection conditions are engaged. Do not apply another province’s age boundary. A report should reach the appropriate child-protection authority; telling a supervisor alone is insufficient.

Indigenous child and family service laws may apply, with provincial guidance explaining referral to an Indigenous authority where relevant. Establish the child’s legal and service context rather than assuming the provincial process is the only possible authority.''',
['Identify the concern and the child’s age, using the CFCSA reporting threshold.', 'Make the report through the appropriate provincial or Indigenous-authority arrangements and address immediate danger.', 'Record the child’s words, evidence, cultural relationships and actions taken.', 'Coordinate support and participation while distinguishing a report, investigation, agreement and court measure.'],
'Explain who is responding and how the child and family can obtain advocacy, legal advice or a complaint review. Respect the applicable Indigenous jurisdiction and do not delay an urgent safety report while assuming that another organisation will act.',
'A worker hears a serious concern about an 18-year-old and dismisses it because the worker previously practised where adult services began earlier.',
'Check the BC age definition and applicable protection conditions. Make the appropriate report and coordinate support with the young person’s participation. Identify any relevant Indigenous authority and transition arrangements rather than importing the former jurisdiction’s boundary.',
'Using another province’s reporting age or assuming that every Indigenous child’s case follows an identical provincial route.',
[S('BC reporting child abuse', 'https://www2.gov.bc.ca/gov/content/safety/public-safety/protecting-children/reporting-child-abuse', 'policy'), S('Child, Family and Community Service Act', 'https://www.bclaws.gov.bc.ca/civix/document/id/complete/statreg/96046_01')]),
'rights': E(
'''The BC Human Rights Code applies to discrimination in its covered areas, while the Canadian Charter has a distinct scope. Indigenous rights and applicable Indigenous laws must be considered in the actual function, alongside professional cultural-safety responsibilities.

The Freedom of Information and Protection of Privacy Act (FIPPA) generally concerns public bodies, while the Personal Information Protection Act (PIPA) governs covered private organisations. Determine the organisation’s legal status and the information involved before applying collection, disclosure or access rules.''',
['Identify the service decision, relevant right and responsible organisation.', 'Consider accommodation, language, cultural safety and the person’s chosen supports.', 'Check whether FIPPA, PIPA or another specific rule applies to the record and disclosure.', 'Record the lawful purpose, necessary information, reasons and the access, correction or complaint route.'],
'The Office of the Information and Privacy Commissioner for BC addresses matters within FIPPA and PIPA; the Human Rights Tribunal addresses Code complaints. Professional and service complaints are separate. Help the person select the route that can address their concern.',
'A private community provider copies a public health authority’s privacy form and assumes that the same disclosure powers apply.',
'Determine the provider’s actual legal obligations and purpose of sharing. Revise the consent and information process to fit the applicable law, and record what the person was told. Similar work does not establish identical statutory powers.',
'Assuming public-body and private-organisation privacy rules are interchangeable.',
[S('BC Human Rights Code', 'https://www.bclaws.gov.bc.ca/civix/document/id/complete/statreg/96210_01'), S('Personal Information Protection Act', 'https://www.bclaws.gov.bc.ca/civix/document/id/complete/statreg/03063_01'), S('FIPPA', 'https://www.bclaws.gov.bc.ca/civix/document/id/complete/statreg/96165_00')]),
}
