from common import entry as E, source as S
DATA = {
'foundations': E(
'''The Social Workers Registration Act 2003, SWRB Code of Conduct and Core Competence Standards anchor professional practice in Aotearoa New Zealand. Registration and a current practising certificate should be distinguished from an employer’s allocation of duties. Specialist statutory roles have additional requirements.

The competence framework includes practice with Māori and attention to Te Tiriti o Waitangi, culture, relationships and safe professional practice. Ask how the person wants whānau, hapū, iwi or other supporters involved. Cultural safety requires reflection on professional power and the person’s experience, rather than adding a cultural label to an unchanged assessment.''',
['Confirm registration, practising status, competence and the authority required for the task.', 'Discuss the person’s goals, language, cultural supports and preferred whānau involvement.', 'Use supervision to test the effect of bias, colonisation, poverty and institutional barriers on the formulation.', 'Connect CPD to feedback and the current SWRB requirements rather than assuming that attending a course proves competence.'],
'Explain the service complaint route and when a professional concern belongs with SWRB. Health and disability service concerns may also engage the Health and Disability Commissioner (HDC). Identify the actual issue and remedy rather than sending every concern to the same body.',
'A service describes a Māori client as disengaged after arranging meetings without the support person they requested.',
'Ask what made the meetings unsafe or unhelpful and agree how participation should work. Review the earlier interpretation and record the person’s goals and chosen supports. Take the effect of professional and institutional power to supervision, with a concrete change to the next contact.',
'Treating whānau involvement as either automatically required in every decision or automatically excluded by individual consent.',
[S('SWRB Core Competence Standards', 'https://swrb.govt.nz/practice/core-competence-standards/', 'professional-standards'), S('SWRB Code of Conduct', 'https://swrb.govt.nz/practice/code-of-conduct/', 'professional-standards'), S('Social Workers Registration Act 2003', 'https://www.legislation.govt.nz/act/public/2003/0017/latest/whole.html')]),
'care-support': E(
'''Disability Support Services (DSS), Needs Assessment and Service Coordination (NASC), Enabling Good Lives arrangements, health services and ACC have different eligibility and funding roles. Identify the scheme relevant to the person’s circumstances; injury-related support, disability support and older-person services should not be treated as one entitlement.

DSS guidance describes referral to a NASC provider to understand needs and determine eligibility, with relevant supporting evidence. A needs assessment, allocation of funding and a service beginning are separate events. Check the current assessment and funding arrangements rather than relying on an old agency name or contract.''',
['Identify the responsible funder and referral route, including NASC or another applicable service.', 'Describe the person’s goals, daily support needs, environmental barriers and existing support.', 'Check the evidence needed for eligibility and explain the decision and funding allocation separately.', 'Confirm the provider, start date, whānau willingness and contingency for gaps or changing needs.'],
'Ask the relevant assessment or funding body for reasons and the applicable reassessment, review or complaint route. DSS publishes current assessment information. Track disputes with different funders separately and do not describe a referral to another agency as a resolved need.',
'A person with a longstanding disability develops additional support needs after an injury, and two services each suggest the other should pay.',
'Map the needs and the scope of each scheme, obtain the actual eligibility decisions and coordinate the interface. Record interim support and unresolved funding responsibility. Keep the person’s desired outcomes visible while the agencies resolve the dispute.',
'Assuming that one diagnosis, one assessment or one funding approval covers every service need.',
[S('DSS needs assessment services', 'https://www.disabilitysupport.govt.nz/disabled-people/assessment-and-funding/needs-assessment-services', 'policy'), S('DSS access to support', 'https://www.disabilitysupport.govt.nz/disabled-people/assessment-and-funding/how-to-access-support', 'policy')]),
'mca': E(
'''Right 7 of the Code of Health and Disability Services Consumers’ Rights addresses informed choice and consent, presumes competence and preserves choice to the extent of a person’s competence. The Protection of Personal and Property Rights Act 1988 (PPPR) provides routes including welfare guardianship, property orders and enduring powers of attorney.

Where a consumer is not competent and no legally entitled representative is available, Right 7(4) has a specific framework. It is not a general rule that any relative may sign. Read the provision and the particular appointment before identifying who may act and what decision standard applies.''',
['Specify the treatment or other decision and provide the support needed for participation.', 'Identify the applicable consent or PPPR framework and record decision-specific evidence.', 'Verify the scope and operation of any enduring power of attorney or court order.', 'If relying on Right 7(4), check its conditions, efforts to ascertain the person’s views and consultation requirements.'],
'HDC and the independent advocacy service provide routes concerning consumer rights. PPPR court orders and representative disputes may require Family Court or other legal advice. The appropriate review depends on whether the issue is a service breach, capacity decision or representative’s authority.',
'A woman can express a clear preference about treatment but needs information presented in short sessions. Her son says he should sign because he manages her bills.',
'Provide the communication support and assess the relevant decision. Financial help does not establish healthcare authority. Read any appointment and use the applicable consent framework, preserving the woman’s own choices to the extent she can make them.',
'Treating diminished competence as loss of every choice or assuming financial authority includes healthcare.',
[S('HDC consent and competence guidance', 'https://www.hdc.org.nz/education/online-learning/consent-for-consumers-who-are-not-competent/', 'policy'), S('Protection of Personal and Property Rights Act 1988', 'https://www.legislation.govt.nz/act/public/1988/0004/latest/whole.html')]),
'dols': E(
'''Restrictions may engage the New Zealand Bill of Rights Act 1990, the consumer Code, PPPR arrangements and, in specific circumstances, compulsory mental-health or intellectual-disability legislation. A welfare guardian or service plan is not an explanation for every measure used by staff.

Identify whether the measure is an ordinary supported-care arrangement, restraint, seclusion or confinement under a specific statutory power. The Intellectual Disability (Compulsory Care and Rehabilitation) Act 2003 has a particular statutory scope; intellectual disability alone does not bring every person within it.''',
['Describe actual restrictions and the person’s wishes, including what happens when they want to leave.', 'Identify the applicable service standard and separate consent, representative authority and any compulsory-care power.', 'Obtain specialist advice about the scope of the order or legal basis where confinement is proposed.', 'Document alternatives, authorisation, monitoring, independent support and a plan to reduce restrictions.'],
'Consumer-rights complaints and advocacy are available through the HDC framework. Where a person is under the compulsory mental-health or intellectual-disability Acts, district inspectors have specific rights-protection functions. Identify the applicable court or tribunal review rather than assuming a single liberty procedure.',
'A residential provider uses a locked room when a resident becomes distressed and says the welfare guardian approved the behaviour plan.',
'Assess immediate safety, the purpose and effect of isolation and the person’s experience. Check the guardian’s powers and the specific legal and service requirements for the measure. Explore communication, environmental and staffing changes, and escalate any missing authority or safeguard.',
'Treating a care plan, guardian’s agreement or disability diagnosis as universal authority for confinement.',
[S('New Zealand Bill of Rights Act 1990', 'https://www.legislation.govt.nz/act/public/1990/0109/latest/whole.html'), S('PPPR Act 1988', 'https://www.legislation.govt.nz/act/public/1988/0004/latest/whole.html'), S('District inspectors and rights protection', 'https://www.health.govt.nz/regulation-legislation/mental-health-and-addiction/mental-health-act/mental-health-district-inspectors', 'policy')]),
'mha': E(
'''The Ministry of Health states that the Mental Health Act 2026 received Royal Assent on 9 July 2026 and is to commence on 1 July 2028. Until replacement takes effect, the Mental Health (Compulsory Assessment and Treatment) Act 1992 remains the operative framework. Preparation for the new system must be distinguished from present powers and rights.

Under the 1992 framework, compulsory assessment and treatment require the statutory mental-disorder criteria and staged procedures. Clinical disagreement, unusual beliefs or a diagnosis alone do not establish all criteria. Use the current Ministry guidelines and authorised clinical roles for the particular stage.''',
['Check whether the operative 1992 route or a subsequently commenced provision applies.', 'Assess the actual mental-disorder and risk or self-care evidence against the relevant statutory criteria.', 'Identify the required clinical assessment, notices, review stage and the person’s cultural and whānau support.', 'Separate compulsory psychiatric treatment from unrelated healthcare consent and discharge-support decisions.'],
'District inspectors are independent lawyers who explain rights, investigate concerns and help with access to review. Judicial or Mental Health Review Tribunal processes depend on legal status. Explain the person’s current rights using the Ministry’s accessible materials and arrange legal support where needed.',
'A team wants to apply a future provision of the 2026 Act because it has been included in a training presentation.',
'Confirm the commencement date and use the operative legislation and forms for the person’s present assessment. Explain current district-inspector and review rights. Record preparation for the new law as service development, not as the authority for today’s intervention.',
'Treating the 2026 Act as fully operational before its commencement.',
[S('Mental-health replacement and commencement', 'https://www.health.govt.nz/regulation-legislation/mental-health-and-addiction/repealing-and-replacing-the-mental-health-act', 'policy'), S('Guidelines to the 1992 Act', 'https://www.health.govt.nz/publications/guidelines-to-the-mental-health-compulsory-assessment-and-treatment-act-1992', 'policy'), S('Current mental-health rights', 'https://www.health.govt.nz/regulation-legislation/mental-health-and-addiction/mental-health-act/your-rights-under-the-mental-health-act', 'policy')]),
'safeguarding': E(
'''Adult safety concerns can engage police, health or disability services, provider safeguarding arrangements, the HDC framework and specific criminal-law duties. There is no reason to assume that one overseas adult-protection procedure applies across these settings.

The Crimes Act 1961 includes offences concerning ill-treatment or neglect and failure to protect a child or vulnerable adult in defined circumstances. Check the actual duty and the person’s role; do not simplify it into a universal reporting rule for every adult concern. DSS quality and safeguarding arrangements relate to the services within its remit.''',
['Identify immediate danger, the adult’s wishes and a safe way to communicate.', 'Choose the relevant police, provider, funder or health/disability complaint route for the facts and setting.', 'Check any specific legal duty and act promptly where its conditions apply.', 'Arrange practical support and follow-up alongside reporting, including continuity if a carer or worker is removed.'],
'HDC complaints and independent advocacy can address health and disability consumer rights. Police and the courts address different issues. Record which body has accepted responsibility and how the adult can raise concerns about the response.',
'An adult using funded support reports that a worker withholds meals as punishment but fears losing the service if they complain.',
'Establish immediate access to food and safe support, hear the adult privately and preserve the relevant facts. Follow the appropriate safeguarding and complaint routes and consider criminal duties or police involvement. Plan continuity so reporting does not leave the person without essential assistance.',
'Assuming a provider incident report resolves all legal duties or covers safety outside the provider’s remit.',
[S('DSS quality and safeguarding responsibilities', 'https://www.disabilitysupport.govt.nz/providers/quality-and-safeguarding/we-can-all-contribute-to-quality-and-safeguarding', 'policy'), S('Crimes Act 1961', 'https://www.legislation.govt.nz/act/public/1961/0043/latest/whole.html')]),
'children': E(
'''The Oranga Tamariki Act 1989 provides the care-and-protection framework, including reports of concern and family group conferences. Current Oranga Tamariki practice guidance explains assessment, referral, preparation, participation and implementation. A family group conference is a statutory process with defined roles, not simply an informal family meeting.

Establish the child’s safety and views alongside whānau relationships, cultural identity and practical support. Use the current Act and policy for duties and powers; professional commitments to culturally safe practice should not be confused with an assumption that every historical statutory provision remains unchanged.''',
['Record the concern and use the appropriate Oranga Tamariki or police route where needed.', 'Distinguish the assessment, the basis for believing care or protection is needed and any referral for a family group conference.', 'Prepare the child and whānau to understand the concern and participate, with the appropriate coordinator and supports.', 'Record the agreed plan, responsible parties and review, and escalate when the plan is not meeting the child’s needs.'],
'Explain participation, support and any applicable court or complaint route. A plan should preserve the child’s voice and show who accepted each action. The statutory process and a practice model do not remove the need for evidence about actual safety.',
'A conference agrees that relatives will support a child, but nobody confirms transport, sleeping arrangements or who will supervise overnight.',
'Translate the broad agreement into a practical plan with named responsibilities and the child’s view. Verify that the arrangements are available and safe. Use the appropriate review or reconvening process if the plan does not meet the needs identified.',
'Treating agreement at a family meeting as proof that a safe, authorised and deliverable plan exists.',
[S('Oranga Tamariki Act 1989', 'https://www.legislation.govt.nz/act/public/1989/0024/latest/whole.html'), S('Family group conference policy', 'https://practice.orangatamariki.govt.nz/policy/family-group-conferences-for-care-andor-protection-concerns', 'policy')]),
'rights': E(
'''The Code of Health and Disability Services Consumers’ Rights, Human Rights Act 1993, New Zealand Bill of Rights Act 1990 and professional standards answer different rights questions. Establish the provider and function involved before choosing the relevant route.

The Privacy Act 2020 and Health Information Privacy Code govern information handling in their respective scope. The Privacy Commissioner publishes a version of the Health Information Privacy Code in force from 1 May 2026, reflecting the new indirect-collection requirements. Use that current version rather than an unchanged 2020 download.''',
['Identify the consumer right, equality issue or public-function decision affecting the person.', 'Ask about language, cultural safety, whānau involvement and accessible participation.', 'Check the applicable privacy rules for collection, notification, use and disclosure; rule 11 governs health-information disclosure.', 'Explain the relevant HDC, advocacy, privacy or other complaint and review route.'],
'A serious-threat exception to health-information confidentiality has conditions, including necessity and the applicable requirements concerning authorisation. Use the current Privacy Commissioner guidance and record the reasoning. A police request is not automatically a direction to release a whole file.',
'A worker receives sensitive health information from a relative and later receives a police request for the entire record.',
'Check the current collection-notification requirements and any applicable exception, then assess disclosure separately. Establish the police request’s purpose and legal basis, share only what the applicable rule permits and document the person’s participation or why authorisation could not appropriately be sought.',
'Using an outdated privacy-code version or treating collection and disclosure as the same legal decision.',
[S('Current Health Information Privacy Code', 'https://www.privacy.org.nz/privacy-principles/codes-of-practice/hipc2020/', 'policy'), S('Health-information disclosure guidance', 'https://www.privacy.org.nz/privacy-principles/codes-of-practice/hipc2020/hipc-factsheet-3/', 'policy'), S('Requests from police and law enforcement', 'https://www.privacy.org.nz/responsibilities/releasing-personal-information-to-police-and-law-enforcement-agencies/', 'policy')]),
}
