from common import entry as E, source as S

DATA = {
'foundations': E(
'''The Northern Ireland Social Care Council (NISCC) Standards of Conduct and Practice provide the professional framework for registered social workers. Distinguish those standards from the procedures of a Health and Social Care (HSC) Trust and from powers available only to a specifically trained or appointed practitioner.

HSC Trusts provide important health and social-care functions; the Regulation and Quality Improvement Authority (RQIA) has a separate service-regulation role. Identify the actual decision-maker and employer. A concern about a worker’s professional conduct, a provider’s quality and a Trust’s care decision may need different responses.''',
['Explain the purpose of contact, professional role and confidentiality limits in accessible language.', 'Identify the HSC Trust, provider and any statutory appointment relevant to the task.', 'Use supervision to test how poverty, disability, trauma or barriers to services influence the formulation.', 'Link learning and feedback to the current NISCC registration and professional-development requirements.'],
'Explain the relevant Trust or provider complaint route and when a concern about a registered worker belongs with NISCC. Give the person a clear account of who can address the outcome they seek; professional regulation does not itself arrange a care package.',
'A family receives different explanations from a Trust worker and a commissioned provider about why visits have reduced.',
'Establish who changed the assessed plan and who changed delivery. Obtain the recorded decision and reasons, hear the person’s experience and address immediate unmet needs. Escalate the appropriate assessment or contract issue instead of referring every complaint to the professional regulator.',
'Treating “the Trust decided” as sufficient explanation without identifying the decision, authority and reasons.',
[S('NISCC Standards and Guidance', 'https://niscc.info/standards-and-guidance/', 'professional-standards')]),
'care-support': E(
'''An HSC Trust needs assessment is the starting point for community support. The Health and Personal Social Services (Northern Ireland) Order 1972 and the Carers and Direct Payments Act (Northern Ireland) 2002 form part of the legal map. Establish the particular duty, Trust criteria and service being requested.

Direct payments can allow an eligible person to arrange assessed support. Discuss the option during assessment, including consent, the ability to manage it with support, permitted use and employer responsibilities. A carer’s own assessment concerns their caring role and needs; it does not replace the assessment of the person receiving care.''',
['Describe the person’s needs and desired outcomes, including fluctuation and the effect of unavailable support.', 'Ask the Trust to explain the assessment and eligibility decisions separately from costs and provision.', 'Offer a carer’s assessment where the relevant conditions are met, including consideration of young carers.', 'Compare arranged services with direct payments and confirm that the proposed support can actually be delivered.'],
'Request reasons, reassessment where circumstances change and the appropriate Trust complaint or review route. Record interim arrangements and unmet needs while a decision is disputed. NI Direct explains access, carers’ assessments and direct payments, with links to local services.',
'A disabled parent needs morning assistance. Their teenager is missing school to help, and a relative suggests using the parent’s benefits to pay informally.',
'Assess the parent’s support needs and the impact on the young person. Consider Trust-arranged care or an eligible direct-payment arrangement with proper support. Clarify funding and employment responsibilities; do not assume the child can continue filling a gap in services.',
'Confusing the carer’s support with services for the cared-for person, or describing an unpaid family arrangement as an agreed funded plan.',
[S('Arranging health and social care', 'https://www.nidirect.gov.uk/articles/arranging-health-and-social-care', 'policy'), S('Direct payments for care', 'https://www.nidirect.gov.uk/articles/direct-payments-care', 'policy'), S('Carers and Direct Payments Act (Northern Ireland) 2002', 'https://www.legislation.gov.uk/nia/2002/6/contents')]),
'mca': E(
'''The Mental Capacity Act (Northern Ireland) 2016 is only partly commenced. Phase 1 covers research and specified deprivation-of-liberty and money-and-valuables provisions. Do not apply the whole Act as though it were already the general framework for every treatment or welfare decision.

Within the operative framework, the assessment is decision-specific, with support before a conclusion of incapacity. The inability must result from impairment or disturbance of the mind or brain. Test understanding, retaining information for the decision, appreciating its relevance and using and weighing it, and communicating the choice. Record how any failed ability affects this decision, rather than relying on a diagnosis. The principles address capacity and best interests. Formal assessments and other statutory functions have training and qualification requirements. A nominated person must be consulted in the relevant process; the role does not confer general substitute decision-making authority.''',
['Identify the proposed act and confirm that the provision being relied on is commenced for that purpose.', 'Specify the decision and provide practical support before applying the relevant capacity test.', 'Check whether the required assessment must be completed by a suitably qualified and trained person.', 'Record the person’s wishes, consultation and the actual legal basis for any decision taken without their own consent.'],
'For phase-1 deprivation-of-liberty decisions, check the Review Tribunal route and safeguards in the current Code, forms and interim guidance. For another type of decision, obtain advice about the applicable law rather than extending phase-1 powers by analogy.',
'A hospital team asks a nominated person to sign consent for an unrelated operation because a deprivation-of-liberty assessment has been completed.',
'Separate the operation from the liberty arrangements. Check the patient’s ability to decide about that treatment and the applicable consent law. The nominated-person role and a liberty assessment do not provide a general consent signature for another intervention.',
'Assuming full commencement or treating the nominated person as a universal decision-maker.',
[S('Mental Capacity Act: implementation and current guidance', 'https://www.health-ni.gov.uk/topics/mental-capacity-act', 'policy'), S('Mental Capacity Act FAQs', 'https://www.health-ni.gov.uk/articles/mental-capacity-act-faqs', 'policy'), S('Mental Capacity Act (Northern Ireland) 2016', 'https://www.legislation.gov.uk/nia/2016/18/contents')]),
'dols': E(
'''The operative deprivation-of-liberty provisions of the Mental Capacity Act (Northern Ireland) 2016 require the relevant assessments, authorisation and safeguards. Setting, age, purpose and the applicable mental-health or children’s framework must be established before selecting a route.

The Department of Health states that the Supreme Court judgment of 2 June 2026 changed the previous approach to defining deprivation of liberty. Interim guidance is available while the Code and other material are reviewed. Read that guidance with current Trust specialist advice; an older training slide is not sufficient evidence of the current legal test.''',
['Describe actual arrangements and obtain evidence about the person’s wishes, understanding and objections.', 'Consult the current interim guidance before deciding whether the arrangements amount to deprivation of liberty.', 'Use the appropriate trained assessors, Trust process and current forms where an authorisation is required.', 'Keep capacity, best interests, authorisation, consultation and challenge arrangements separately recorded.'],
'Identify the nominated person, advocacy or representation required and the person’s access to the Review Tribunal. Check expiry, review and changed circumstances. Do not remove an existing safeguard solely because a judgment or guidance has changed without the responsible legal review.',
'A care setting continues to use an old checklist after June 2026 and says its completed form proves all arrangements are lawful.',
'Review the actual restrictions and the source version used. Ask the Trust’s MCA team to apply the current guidance and determine any required reassessment or authorisation. Continue meeting immediate care and participation duties while resolving the legal position.',
'Treating an old definition, a completed form or family approval as a complete legal analysis.',
[S('Interim guidance on the Mental Capacity Act (NI) 2016', 'https://www.health-ni.gov.uk/publications/interim-guidance-mental-capacity-act-ni-2016', 'policy'), S('Mental Capacity Act FAQs', 'https://www.health-ni.gov.uk/articles/mental-capacity-act-faqs', 'policy')]),
'mha': E(
'''The Mental Health (Northern Ireland) Order 1986 remains relevant alongside the partly commenced capacity legislation. Assessment and treatment routes have their own criteria and professional roles. For admission for assessment, the Order includes mental disorder of a nature or degree warranting detention for assessment and the relevant substantial likelihood of serious physical harm.

An approved social worker has specific training and functions. The medical recommendation, application and hospital processes should be distinguished. A general referral to mental-health services is not a compulsory admission application.''',
['Identify voluntary support and whether an assessment or treatment detention route is actually being considered.', 'Check the current Order, evidence for the particular criteria and the authorised professional’s role.', 'Keep the partly commenced capacity framework and any separate physical-treatment decision distinct.', 'Explain the person’s status and arrange rights information, support and review under the applicable route.'],
'The Review Tribunal and the relevant hospital discharge or review processes address detention questions. Help the person obtain advice and understand how to challenge the measure. Confirm which rules apply to their specific admission status and documents.',
'A person declines admission after an argument at home but agrees to a same-day assessment and support from a trusted friend.',
'Explore the immediate safety evidence, physical health and whether voluntary arrangements are workable. Ask the authorised professionals to assess the actual statutory criteria if compulsion is proposed. Refusal of the first offer is not itself the required harm analysis.',
'Assuming the 2016 capacity legislation has replaced every mental-health admission provision.',
[S('Mental Health (Northern Ireland) Order 1986', 'https://www.legislation.gov.uk/nisi/1986/595/contents'), S('Mental health services and support', 'https://www.nidirect.gov.uk/articles/mental-health-services-and-support', 'policy')]),
'safeguarding': E(
'''The regional policy Adult Safeguarding: Prevention and Protection in Partnership distinguishes an adult at risk of harm from an adult in need of protection. It considers personal characteristics and life circumstances, with HSC Trust and PSNI roles according to the concern. It is not a general power to compel an adult to accept services.

The Adult Protection Bill is a reform to monitor, not a source of powers to assume are already operational. The Assembly’s legislative tracker must be checked for passage and any subsequent Act and commencement before applying a new duty.''',
['Identify abuse, exploitation or neglect and the adult’s ability to protect themselves in their actual circumstances.', 'Use the organisation’s safeguarding arrangements and refer protection concerns to the appropriate HSC Trust route.', 'Contact PSNI where the circumstances require a police response, distinguishing criminal investigation from the support plan.', 'Establish the lawful basis for information sharing and for any proposed intervention without agreement.'],
'Use the policy’s participation and proportionate-response approach, together with the applicable consent, capacity and legal safeguards. Explain the Trust or provider complaint process and obtain specialist advice if a coercive intervention is proposed.',
'An isolated adult says a neighbour takes their pension but fears losing the only person who buys groceries.',
'Arrange a safe conversation and practical alternatives for food and contact. Assess the protection concern and report through the relevant Trust and police routes as appropriate. A refusal of one intervention does not remove the need to explore coercion, dependency and a safer support plan.',
'Treating a safeguarding policy as a detention power or treating a proposed Bill as commenced law.',
[S('Adult safeguarding policy and documents', 'https://www.health-ni.gov.uk/publications/adult-safeguarding-prevention-and-protection-partnership-key-documents', 'policy'), S('Assembly legislation tracker', 'https://www.niassembly.gov.uk/assembly-business/legislation/2022-2027-mandate/primary-legislation-bills-22-27-mandate/', 'policy')]),
'children': E(
'''The Children (Northern Ireland) Order 1995 provides the main framework for children in need, family support and protective court processes. Co-operating to Safeguard Children and Young People supplies the regional policy framework. The HSC Trust’s children’s services and PSNI have different responsibilities.

Assessment and family support should be distinguished from a protection investigation or court order. A family meeting cannot create powers of removal or determine legal parental responsibility. Check the child’s position and the relevant authority for accommodation, contact and treatment decisions.''',
['Record the child’s account, daily experience, harm concerns and support needs.', 'Use the current regional policy and Trust referral procedure for a child-protection concern.', 'Identify who holds parental responsibility and any court order affecting the proposed decision.', 'Coordinate education, health and family support and plan transitions before a service ends.'],
'Explain the particular assessment, protection or court process, including how the child and family can participate, obtain advocacy or legal advice and raise disagreement. Do not promise confidentiality that conflicts with a necessary safeguarding response.',
'A child tells a school worker they are frightened to return home. The parent asks for the conversation to remain within school.',
'Listen without leading questions, record the child’s words and assess immediate safety. Follow the relevant Trust and police referral arrangements where required. Explain confidentiality limits safely and establish who will act before the child leaves the setting.',
'Allowing an internal discussion or a parent’s request for secrecy to replace the required protection response.',
[S('Children (Northern Ireland) Order 1995', 'https://www.legislation.gov.uk/nisi/1995/755/contents'), S('Co-operating to safeguard children and young people', 'https://www.health-ni.gov.uk/publications/co-operating-safeguard-children-and-young-people-northern-ireland', 'policy')]),
'rights': E(
'''Northern Ireland has its own equality laws. The Equality Act 2010 does not apply. Identify the relevant disability, sex, race, religious or political discrimination provision and the setting it covers. Section 75 of the Northern Ireland Act 1998 places equality-of-opportunity and good-relations duties on designated public authorities.

The Human Rights Act and applicable UK data-protection law also matter, but they answer different questions. A public authority’s equality scheme does not by itself establish permission to disclose a person’s health information.''',
['Identify the relevant equality law and public-authority duty for the actual decision.', 'Arrange accessible communication and consider the applicable reasonable-adjustment obligations.', 'Establish the purpose and legal basis of sharing, including the treatment of sensitive information.', 'Record the person’s account, alternatives, reasons, disagreement and the route for correction or challenge.'],
'The Equality Commission for Northern Ireland provides information on discrimination and routes to challenge. Distinguish a service complaint, an equality-scheme concern and legal proceedings; obtain timely advice because different limits and remedies apply.',
'A service offers an assessment in an inaccessible building and says its policy treats every applicant identically.',
'Identify the disability-related barrier and the applicable adjustment duty. Offer an accessible arrangement and revisit any adverse inference caused by the failed appointment. Record the change and how the person can challenge the earlier decision.',
'Copying an equality test from another legal system or equating identical treatment with accessible participation.',
[S('Equality laws in Northern Ireland', 'https://equalityni.org/equality-laws-ni', 'policy'), S('Section 75 and equality schemes', 'https://equalityni.org/public-authorities/section-75', 'policy'), S('Northern Ireland Act 1998, section 75', 'https://www.legislation.gov.uk/ukpga/1998/47/section/75')]),
}
