from common import entry as E, source as S

DATA = {
'foundations': E(
'''The Scottish Social Services Council (SSSC) Codes of Practice apply to workers and employers. The revised Codes took effect on 1 May 2024. Professional registration and employer procedures serve different purposes: an employer can allocate work but cannot confer a statutory appointment or qualification that a particular function requires.

Identify the responsible local authority, Health and Social Care Partnership, NHS service or voluntary organisation. Integration does not remove the need to identify who is exercising a duty, holding a record or making a funding decision. The SSSC regulates the workforce; the Care Inspectorate regulates registered care services.''',
['Explain your SSSC role, employer and the purpose of involvement; check any specialist appointment required for the work.', 'Use an outcomes conversation to connect daily living, relationships, poverty and service barriers to an assessment.', 'Take a conflict between resources and assessed need to supervision with evidence and a proposed response.', 'Link continuous professional learning to feedback and a change in practice, using the current SSSC requirements.'],
'Use the employer’s complaints process for a service decision and the SSSC route for a concern about a registered worker’s fitness to practise. Explain that these address different questions. A complaint to a regulator does not automatically review a funding decision.',
'A worker is asked to close a referral because a family has missed two appointments. The person says bus fares and caring duties prevented attendance.',
'Test the access barrier before concluding that support is unwanted. Offer a workable contact method, clarify the person’s outcomes and record the referral decision and its reasons. In supervision, distinguish a resource pressure from evidence about need and willingness.',
'Treating an employer instruction as the complete explanation for a professional decision.',
[S('SSSC Codes of Practice', 'https://www.sssc.uk.com/standards/codes-of-practice/', 'professional-standards')]),
'care-support': E(
'''Community care sits across the Social Work (Scotland) Act 1968, the Social Care (Self-directed Support) (Scotland) Act 2013 and the Carers (Scotland) Act 2016. Identify the relevant assessment duty and local eligibility policy. A budget calculation is a different step from identifying the person’s needs.

The 2025 statutory SDS guidance describes four options: a direct payment; support selected by the person and arranged through the authority or an agreed third party; support selected and arranged by the authority with the person; or a combination. Discuss the choices rather than treating one option as the default.''',
['Assess personal outcomes and explain which community-care duty and eligibility policy are being applied.', 'Offer and explain the four SDS options, including practical assistance with managing the chosen arrangement.', 'Consider an adult carer support plan or young carer statement separately from the cared-for person’s assessment.', 'Record the support budget, any charging decision, agreed provision and how unmet needs will be escalated.'],
'Ask for the authority’s written reasons and information about reconsideration or complaints when assessment, eligibility or provision is disputed. Use the current SDS and carers guidance for the particular issue. Independent advocacy and accessible information can make participation effective.',
'An adult wants assistance to attend evening activities, while a parent asks the authority to arrange all daytime support.',
'Explore the adult’s outcomes and whether a combination of SDS options would fit. Establish what the parent is willing to do and any need for a separate carer plan. Confirm actual evening provision, management support and costs before describing the package as agreed.',
'Presenting SDS as direct payments only, or treating a relative’s preference as the adult’s choice.',
[S('SDS statutory guidance, updated 2025', 'https://www.gov.scot/publications/statutory-guidance-accompany-social-care-self-directed-support-scotland-act-2013-updated-2025/', 'policy'), S('Social Care (Self-directed Support) (Scotland) Act 2013', 'https://www.legislation.gov.uk/asp/2013/1/contents'), S('Carers (Scotland) Act 2016', 'https://www.legislation.gov.uk/asp/2016/9/contents')]),
'mca': E(
'''The Adults with Incapacity (Scotland) Act 2000 (AWI) provides different routes for welfare, property and treatment decisions. Its principles require benefit that cannot reasonably be achieved without intervention, the least restrictive option, attention to the adult’s wishes, consultation with relevant people, and encouragement of the adult’s skills.

For the matter in question, AWI incapacity concerns inability to act, decide, communicate or understand a decision, or remember it, because of mental disorder or inability to communicate caused by physical disability. A communication difficulty that human or mechanical assistance can resolve does not itself satisfy the definition. A welfare attorney, guardian or person holding an intervention order has only the powers actually conferred. A financial appointment does not provide general welfare authority.''',
['Identify the decision and use communication support before concluding that the adult cannot act or decide.', 'Apply the AWI principles to the proposed intervention and describe the benefit sought.', 'Read any power of attorney or court order and check scope, activation and limits.', 'For medical treatment, check the Part 5 certification and treatment framework with the responsible clinician; do not treat a social-work assessment as clinical authorisation.'],
'Disagreement about a proxy, treatment or a court order requires the relevant AWI route, not simply a majority vote at a meeting. The Mental Welfare Commission provides rights information; the Office of the Public Guardian and sheriff court have different functions depending on the issue.',
'A man can choose his meals and visitors but struggles to understand a proposed sale of his home. His sister holds a welfare power of attorney.',
'Keep the property decision distinct from daily choices and welfare matters. Provide accessible financial information and check the document’s powers. Do not let the welfare appointment stand in for financial authority. Explain which advice or court process is needed if the sale remains necessary and authority is missing.',
'Using a global incapacity label or assuming that any attorney can make every decision.',
[S('AWI principles', 'https://www.gov.scot/publications/adults-with-incapacity-act-principles/', 'policy'), S('Adults with Incapacity (Scotland) Act 2000', 'https://www.legislation.gov.uk/asp/2000/4/contents'), S('Mental Welfare Commission: your rights', 'https://www.mwcscot.org.uk/looking-help/your-rights', 'policy')]),
'dols': E(
'''Scottish restrictions require analysis under the applicable welfare, mental-health and human-rights framework. There is no English hospital/care-home authorisation scheme to copy. AWI welfare guardianship or an intervention order may be relevant, but the wording and lawful scope of a particular order matter.

Distinguish agreement to support, authority for a welfare decision and the legal justification for actual confinement. Where arrangements may engage Article 5, obtain current advice about the applicable legal test and route. A service’s description of a placement as voluntary does not resolve what happens if the person wants to leave.''',
['Describe the actual restrictions and the person’s responses, including attempted departures and staff interventions.', 'Identify whether the proposed authority is an AWI order, a mental-health measure or another lawful route.', 'Read the exact powers and seek specialist advice where confinement or disputed authority is involved.', 'Arrange a less restrictive plan, independent support and a named review of necessity and objections.'],
'Use the court or tribunal route appropriate to the actual measure. The Mental Welfare Commission can advise about rights and concerns. A welfare order and a compulsory mental-health order should not be described as interchangeable, and neither removes the need to review everyday restrictions.',
'A supported-living service locks the front door at night and says a guardian agreed to the placement. The adult repeatedly asks to leave.',
'Obtain the order and distinguish placement powers from the measures staff enforce. Record the adult’s wishes, actual ability to leave and alternatives such as staffing or environmental changes. Escalate the legal basis of confinement promptly and arrange support to challenge it; family approval is insufficient reasoning.',
'Assuming that guardianship automatically authorises every restriction used by a provider.',
[S('Adults with Incapacity (Scotland) Act 2000', 'https://www.legislation.gov.uk/asp/2000/4/contents'), S('Mental Welfare Commission: your rights', 'https://www.mwcscot.org.uk/looking-help/your-rights', 'policy')]),
'mha': E(
'''The Mental Health (Care and Treatment) (Scotland) Act 2003 provides emergency, short-term and longer-term compulsory routes, with amendments including the Mental Health (Scotland) Act 2015. A Mental Health Officer (MHO) has a specific statutory role; being a social worker does not itself confer that appointment.

For a compulsory treatment order, the criteria concern mental disorder, available treatment, significant risk without treatment, significantly impaired decision-making ability about medical treatment because of the disorder, and necessity. The exact criteria differ between routes. Significantly impaired decision-making ability is not simply another name for the AWI incapacity test.''',
['Identify whether emergency detention, short-term detention or an application for a compulsory treatment order is proposed.', 'Map evidence to that route’s criteria, including the contribution of voluntary and community alternatives.', 'Identify the responsible medical professionals, MHO and Mental Health Tribunal for Scotland functions.', 'Separate psychiatric treatment safeguards from the authority for unrelated physical healthcare.'],
'Explain access to independent advocacy, the named-person arrangements that apply, legal representation and tribunal review. Particular treatments have additional safeguards. Use the Mental Welfare Commission rights guidance and the actual order when explaining the person’s position.',
'A person experiencing severe mental distress declines admission but accepts daily support and an urgent medical review at home.',
'Assess whether the proposed community support is real and sufficient, and compare it with the relevant statutory criteria. Record the person’s reasoning and the MHO’s assessment. Do not substitute disagreement with the recommended treatment for evidence of significantly impaired decision-making ability or necessity.',
'Using one detention threshold for every route, or equating refusal with the statutory decision-making criterion.',
[S('Mental Health (Care and Treatment) (Scotland) Act 2003', 'https://www.legislation.gov.uk/asp/2003/13/contents'), S('Mental Welfare Commission: your rights', 'https://www.mwcscot.org.uk/looking-help/your-rights', 'policy'), S('SIDMA practice guidance', 'https://www.mwcscot.org.uk/node/510', 'policy')]),
'safeguarding': E(
'''The Adult Support and Protection (Scotland) Act 2007 concerns adults aged 16 or over meeting all three criteria: inability to safeguard their own wellbeing, property, rights or interests; risk of harm; and greater vulnerability to harm because of disability, mental disorder, illness or physical or mental infirmity. Capacity is not a separate gateway requirement.

The council’s inquiry duty, investigative powers and protection orders are distinct. The three criteria are not an eligibility test for ordinary support. A finding that this Act is not the appropriate route should lead to consideration of other available help, rather than automatic case closure.''',
['Refer concerns on the basis of the available evidence; a referrer need not prove that all criteria are met.', 'Consider each criterion explicitly in council inquiries and revisit it as circumstances change.', 'Identify the council officer’s role, partner-agency responsibilities and any need for police involvement.', 'Apply the Act’s benefit and least restrictive principles, consider advocacy and distinguish support from compulsory powers.'],
'The 2022 Code explains participation, consent and the safeguards around investigations and protection measures. Seek the relevant legal advice before coercive action; a protection concern does not confer unlimited entry, removal or treatment powers.',
'A 61-year-old understands their bank account but depends on a neighbour who takes their money and controls access to shopping.',
'Do not reject the concern because the adult can explain the transactions. Explore dependency, coercion and ability to safeguard their interests against the three criteria. Arrange a safe conversation, practical access to essentials and the appropriate council and police response.',
'Treating capacity as proof that an adult can protect themselves, or using protection criteria to deny ordinary services.',
[S('Adult Support and Protection (Scotland) Act 2007', 'https://www.legislation.gov.uk/asp/2007/10/contents'), S('2022 adult protection guidance', 'https://www.gov.scot/publications/adult-support-protection-scotland-act-2007-guidance-general-practice/pages/2/', 'policy')]),
'children': E(
'''The Children (Scotland) Act 1995 and Children’s Hearings (Scotland) Act 2011 provide important duties and compulsory-measure routes. GIRFEC is the national practice framework for coordinated support. Its SHANARRI wellbeing indicators organise enquiry; they do not replace the legal grounds and safeguards for a compulsory measure.

A child’s plan and a lead professional can coordinate services. Referral to the Children’s Reporter and decisions in the hearings system are separate from an ordinary support meeting. Explain which process is being used, why, and how the child and family can participate.''',
['Use the child’s account and daily-life evidence alongside family strengths and protection concerns.', 'Apply GIRFEC and current national child-protection guidance without treating a wellbeing concern as automatic compulsory authority.', 'Identify whether local-authority support, a protection response or a referral to the Reporter is required.', 'Plan transitions with education, health and adult services, verifying actual acceptance and continuing responsibilities.'],
'Children should receive accessible explanations and appropriate advocacy or legal support for the process affecting them. The UNCRC (Incorporation) (Scotland) Act 2024 adds duties within its statutory scope; check that scope rather than describing every public decision as covered in the same way.',
'A 15-year-old misses school to support an ill parent and says they want to stay at home but need help.',
'Explore the young person’s safety, education and caring responsibilities. Coordinate support and consider a young carer statement. Establish whether there is evidence requiring a protection or Reporter route, while avoiding a conclusion that school absence alone settles that question.',
'Treating GIRFEC as a power to compel cooperation or assuming adult support will begin automatically at transition.',
[S('GIRFEC framework', 'https://www.gov.scot/policies/girfec/', 'policy'), S('Children (Scotland) Act 1995', 'https://www.legislation.gov.uk/ukpga/1995/36/contents'), S('Children’s Hearings (Scotland) Act 2011', 'https://www.legislation.gov.uk/asp/2011/1/contents')]),
'rights': E(
'''Scottish practice engages the Human Rights Act 1998, Equality Act 2010 and the applicable UK data-protection framework, alongside local statutory duties. The SSSC Codes provide professional expectations; they do not replace the legal basis for an intervention or disclosure.

The UNCRC (Incorporation) (Scotland) Act 2024 strengthens children’s rights within its defined scope. Identify the source of the public function and the statutory limits before asserting that a particular action breaches its compatibility duty. Participation and accessible explanations remain essential to a reasoned assessment.''',
['Identify the actual decision and the public body or service responsible for it.', 'Consider equality barriers and reasonable adjustments in assessment, communication and service access.', 'For information sharing, identify the applicable lawful basis and any additional condition for sensitive data; distinguish confidentiality from data protection.', 'Record reasons, alternatives and disagreement, and explain the organisation’s access, correction and complaints routes.'],
'A service complaint, a data-protection complaint and a court or tribunal challenge have different purposes and timescales. Help the person identify the remedy they seek and obtain advice on the relevant route; an internal review does not necessarily preserve a separate legal deadline.',
'A deaf parent is offered only telephone appointments and is then described as failing to engage with a family assessment.',
'Arrange suitable communication support, correct the inaccurate inference and reassess the effect of the service barrier. Record the parent’s preferred method, the adjustment agreed and responsibility for providing it. Review the assessment outcome in light of the earlier exclusion.',
'Writing that equality was considered without identifying the barrier, adjustment or effect on the decision.',
[S('Children’s rights and incorporation', 'https://www.gov.scot/policies/human-rights/childrens-rights/', 'policy'), S('Equality Act 2010', 'https://www.legislation.gov.uk/ukpga/2010/15/contents'), S('SSSC Codes of Practice', 'https://www.sssc.uk.com/standards/codes-of-practice/', 'professional-standards')]),
}
