from common import entry as E, source as S
DATA = {
'foundations': E(
'''New York Education Law and the Office of the Professions distinguish Licensed Master Social Workers (LMSWs) from Licensed Clinical Social Workers (LCSWs). An LMSW may provide clinical social-work services, including diagnosis, psychotherapy and assessment-based treatment planning, only under the required supervision; an LCSW may provide those services independently within competence.

Licensure, registration, a permitted practice setting and any separate mental-hygiene designation must be checked. Employer seniority does not create a statutory power. Professional ethical guidance should be read alongside state law and applicable agency obligations.''',
['Confirm the licence, current registration, scope and supervision required for the actual work.', 'Explain the professional role, service purpose and confidentiality limits.', 'Check any additional designation or qualification required for a statutory mental-health function.', 'Use supervision and continuing education to improve the effect of practice, including cultural responsiveness and access.'],
'The Office of the Professions addresses professional regulation; benefit decisions, agency services and mental-health detention have different complaint or review routes. Explain which body can address the person’s concern and desired remedy.',
'An LMSW is offered an independent psychotherapy caseload without the supervision required for clinical work.',
'Check the scope, setting and supervision requirements before accepting the arrangement. Arrange appropriate oversight or a lawful alternative and explain the practitioner’s status accurately. A social-work licence does not mean that both licence categories have identical clinical authority.',
'Treating LMSW and LCSW practice permissions as interchangeable.',
[S('NYSED: LMSW and LCSW distinction', 'https://www.op.nysed.gov/professions/social-work/faqs/what-difference-between-lmsw-and-lcsw', 'professional-standards'), S('NYSED social-work laws and rules', 'https://www.op.nysed.gov/professions/licensed-master-social-worker/laws-rules-regulations', 'professional-standards')]),
'care-support': E(
'''Medicaid personal care and Consumer Directed Personal Assistance Services involve assessment, medical necessity and service authorisation. The New York Independent Assessor Program (NYIAP), local departments of social services and managed-care organisations have different responsibilities. An assessment does not itself authorise every requested hour of care.

Current Department of Health guidance includes minimum-needs requirements introduced in 2025 and legacy-status arrangements. Check the person’s programme and circumstances before applying a new rule or assuming that an existing recipient follows the same route as a new applicant.''',
['Identify Medicaid eligibility, the service requested and the responsible assessment and authorisation bodies.', 'Obtain the applicable community assessment and practitioner information through the current NYIAP process.', 'Confirm the plan of care, amount, duration, frequency and actual provider arrangements.', 'Record voluntary informal support, unmet needs and the notice, plan appeal or fair-hearing route for a disputed decision.'],
'Managed-care appeals and state fair hearings depend on the decision and programme. Read the notice for time limits, any required internal step and continued-benefit rules. A complaint to the provider is different from challenging the authorisation.',
'A person receives an assessment but the plan authorises fewer hours than requested, assuming a relative will provide the rest.',
'Check the assessment evidence, the relative’s voluntarily offered assistance and the plan’s written reasons. Identify the appropriate appeal or hearing process and interim safety arrangements. Do not treat an assumed family contribution as available care.',
'Confusing NYIAP assessment with final service authorisation or overlooking current minimum-needs and legacy rules.',
[S('NYIAP roles and responsibilities', 'https://www.health.ny.gov/health_care/medicaid/redesign/nyiap/ldss-mmco.htm', 'policy'), S('NYIAP current policy repository', 'https://www.health.ny.gov/health_care/medicaid/redesign/nyiap/repository/index.htm', 'policy'), S('Minimum-needs and legacy guidance', 'https://www.health.ny.gov/health_care/managed_care/plans/min_needs.htm', 'policy')]),
'mca': E(
'''Healthcare proxies, the Family Health Care Decisions Act (FHCDA) and Mental Hygiene Law Article 81 guardianship are distinct. Check the healthcare setting and statutory scope before using the FHCDA surrogate list. A healthcare proxy or a valid patient decision may need consideration before a default surrogate route. FHCDA capacity concerns understanding and appreciating what the proposed care involves and its consequences, including risks, benefits and alternatives, and making an informed choice. Use the statutory assessment process; a social-work opinion alone does not replace a required practitioner determination.

Article 81 requires a necessity assessment and, where incapacity is alleged, clear and convincing evidence about inability to meet personal or property needs and insufficient understanding and appreciation of that inability, with likely harm. The court should tailor powers and consider available alternatives. A diagnosis alone does not establish the guardianship test.''',
['Specify the decision, support the person and identify the applicable healthcare or guardianship framework.', 'Check any proxy, prior decision or court order and the scope of authority.', 'Where FHCDA applies, use the statutory surrogate priority, eligibility and decision standards.', 'For an Article 81 issue, document functional evidence, likely harm and less restrictive available resources.'],
'The FHCDA includes requirements for surrogate decisions, with additional safeguards for life-sustaining treatment. Article 81 has court procedures and tailored powers. Disagreement about a healthcare choice should not automatically become a request for broad guardianship.',
'A patient’s adult child assumes they can decide because of family status, while a healthcare proxy names a close friend.',
'Assess the patient’s own decision-making ability and check the proxy’s operation and scope. Do not jump to the default surrogate list. If a separate guardianship concern exists, identify its functional evidence and alternatives rather than using it to bypass the healthcare arrangement.',
'Treating family status as priority over every valid appointment or using diagnosis alone to establish Article 81 incapacity.',
[S('FHCDA surrogate decisions', 'https://www.nysenate.gov/legislation/laws/PBH/2994-D'), S('Article 81 guardianship standard', 'https://www.nysenate.gov/legislation/laws/MHY/81.02'), S('Health care proxies, Public Health Law Article 29-C', 'https://www.nysenate.gov/legislation/laws/PBH/A29-C')]),
'dols': E(
'''Mental Hygiene Law Article 9 admission, Article 81 guardianship and facility restraint rules concern different authorities. An Article 81 guardian receives only the powers granted by the court. The personal-needs provisions do not make guardianship a general permission for involuntary psychiatric admission.

Separate a placement decision, the actual restriction on departure and the authority for treatment. An institution should identify the legal basis for each measure and the required review. A family’s agreement or an administrative discharge concern does not establish detention authority.''',
['Describe the restriction, setting, person’s wishes and current legal status.', 'Read the actual Article 9 documents or Article 81 order and identify its limits.', 'Check separate authority and safeguards for restraint or treatment.', 'Arrange Mental Hygiene Legal Service or other appropriate legal support and the relevant court or complaint process.'],
'A court challenge to detention, review of guardianship powers and a service complaint address different matters. Explain the route relevant to the actual restriction. The person should have accessible rights information and help to express and act on objections.',
'A facility says a guardian’s authority to choose residence allows it to admit the adult involuntarily to a psychiatric hospital.',
'Read the order and Article 81 limits, then identify whether Article 9 criteria and procedures are met. Obtain appropriate legal and clinical advice and consider voluntary alternatives. Residence powers should not be used as a substitute for psychiatric admission safeguards.',
'Treating a guardian’s placement power as a universal psychiatric detention power.',
[S('Article 81 personal-needs powers and limits', 'https://www.nysenate.gov/legislation/laws/MHY/81.22'), S('Article 9 emergency admission', 'https://www.nysenate.gov/legislation/laws/MHY/9.39'), S('OMH current admission and transport guidance', 'https://omh.ny.gov/omhweb/guidance/transport-civil-voluntary-involuntary-admissions-statutes.html', 'policy')]),
'mha': E(
'''Mental Hygiene Law Article 9 provides distinct voluntary, emergency and other involuntary-admission routes. Section 9.39 concerns immediate hospital observation, care and treatment where the mental-illness and likely-serious-harm conditions are met. Its current definition includes specified inability or refusal, because of mental illness, to meet essential needs causing substantial risk of physical harm.

Under this route, retention beyond 48 hours requires confirmation by another physician from the psychiatric staff; the emergency period is limited to 15 days. Further retention requires the applicable additional process. These are route-specific limits, not rules to apply indiscriminately to every Article 9 admission.''',
['Identify the exact Article 9 route and evidence for its current criteria.', 'Check the authorised practitioner, examinations, forms, notices and timing.', 'Use the current OMH guidance, including the updated essential-needs wording, and consider voluntary alternatives.', 'Separate detention from treatment authority and coordinate accepted discharge and community-support arrangements.'],
'Section 9.39 requires rights notice and provides a court-hearing route, with Mental Hygiene Legal Service involvement. Different statuses have different review procedures. A treatment-over-objection issue needs its own analysis and should not be assumed resolved by admission.',
'A team assumes emergency admission requires an express threat and ignores evidence that mental illness prevents a person obtaining essential medical care.',
'Apply the current statutory definition and assess the connection to substantial physical harm, rather than relying on a threat-only summary. Consider realistic support and alternatives, record each criterion and explain the person’s rights and review route.',
'Using an outdated threat-only account of serious harm or confusing the time limits of different admission routes.',
[S('Mental Hygiene Law section 9.39', 'https://www.nysenate.gov/legislation/laws/MHY/9.39'), S('OMH admission and transport tables', 'https://omh.ny.gov/omhweb/guidance/transport-civil-voluntary-involuntary-admissions-statutes.html', 'policy'), S('Current OMH guidance and updates', 'https://omh.ny.gov/omhweb/guidance/', 'policy')]),
'safeguarding': E(
'''Social Services Law section 473 provides protective services for adults meeting its conditions, without regard to income. The framework concerns mental or physical impairments affecting ability to manage resources, daily living or protection from harm, together with the absence of someone available, willing and able to assist responsibly.

Local social-services districts provide adult-protective services and coordinate with health, mental-health, legal and other agencies. A general APS referral, a setting-specific mandated report and an application for guardianship are different matters. Do not invent a universal adult-reporting duty from the child-reporting rules.''',
['Identify the harm, functional difficulties and whether responsible assistance is actually available.', 'Refer through the appropriate local adult-protective services route and address immediate danger.', 'Check any separate provider, facility, police or mandated-reporting requirement.', 'Use the least restrictive appropriate response and distinguish voluntary services from court-authorised measures.'],
'The adult’s agreement and participation remain important; an APS referral does not confer general authority to force services. Where a court measure is proposed, identify its own conditions and representation. Explain the local service complaint and relevant legal route.',
'An adult cannot obtain food or manage money because of impairment, and the only relative listed as a contact is unwilling to assist.',
'Assess the actual availability and reliability of help against the protective-service conditions. Arrange immediate practical support and the appropriate APS response. A name on a contact form is not evidence that someone can responsibly meet the need.',
'Assuming that any listed relative rules out APS support or that a referral automatically authorises guardianship.',
[S('Social Services Law section 473', 'https://www.nysenate.gov/legislation/laws/SOS/473'), S('OCFS adult services', 'https://ocfs.ny.gov/programs/adult-svcs/', 'policy')]),
'children': E(
'''Social Services Law sections 413 and 415 identify mandated reporters and reporting procedures. Covered social workers must act on reasonable cause to suspect abuse or maltreatment within the statutory circumstances. The Statewide Central Register route has defined scope, including the relationship of the alleged responsible person to the child.

An immediate report and the required written follow-up are distinct steps; section 415 generally requires the written report within 48 hours. Abuse by someone outside the child-protective reporting definition may still require police or another safety response. Do not treat an out-of-scope SCR decision as proof that no action is needed.''',
['Identify the reporter role, child’s age, alleged responsible person and facts supporting reasonable cause.', 'Use the required SCR reporting process and immediate emergency response where necessary.', 'Complete the applicable written follow-up and document receipt, facts and safety actions.', 'Consider police, institutional or other reporting duties separately and coordinate family support.'],
'Explain the child-protective process and access to support or legal advice. Reporting is not a court determination of abuse or authority for every intervention. Preserve the child’s account and the distinction between an allegation, investigation and finding.',
'A social worker hears a disclosure but is told to wait for a manager to decide whether it is sufficiently certain to report.',
'Assess reasonable cause under the statute and act through the required procedure. Record the relationship and facts that determine the correct recipient. Do not require certainty or delay a required report for an internal meeting.',
'Confusing reasonable cause with proof, or assuming the SCR is the only possible route for every threat to a child.',
[S('Social Services Law section 413', 'https://www.nysenate.gov/legislation/laws/SOS/413'), S('Social Services Law section 415', 'https://www.nysenate.gov/legislation/laws/SOS/415'), S('OCFS child protective services', 'https://ocfs.ny.gov/programs/cps/', 'policy')]),
'rights': E(
'''Federal civil-rights and disability law, New York Human Rights Law and sector-specific patient rights apply according to the service and decision. Identify the responsible body and the actual access barrier or restriction rather than assuming every complaint uses the same route.

HIPAA applies to covered entities and business associates; Mental Hygiene Law section 33.13 protects covered clinical records, and Part 2 provides additional requirements for certain substance-use-disorder records. The 2024 Part 2 changes required compliance by February 2026. Determine which overlapping rules apply before sharing.''',
['Identify the organisation, record and state or federal privacy provisions involved.', 'Arrange accessible communication, interpretation and culturally responsive participation.', 'Check the legal basis, purpose and scope of disclosure, including any special rules for proceedings.', 'Explain records access, correction, complaints and the applicable patient-rights or legal review route.'],
'A privacy complaint, professional complaint and mental-hygiene rights challenge address different questions. A request from police, a lawyer or another service does not itself establish authority to release a whole record. Obtain the relevant advice and document the decision.',
'A mental-health service receives a broad request for records and assumes HIPAA permission alone resolves all confidentiality requirements.',
'Check the record’s coverage under state mental-hygiene law and any Part 2 restrictions as well as HIPAA. Identify the actual request and lawful basis, limit disclosure and explain the person’s rights where appropriate. One applicable rule does not remove another.',
'Checking HIPAA while overlooking state mental-hygiene or specially protected substance-use records.',
[S('Mental Hygiene Law section 33.13', 'https://www.nysenate.gov/legislation/laws/MHY/33.13'), S('HHS mental-health privacy guidance', 'https://www.hhs.gov/hipaa/for-professionals/special-topics/mental-health/index.html', 'policy'), S('Current Part 2 requirements', 'https://www.hhs.gov/hipaa/part-2/index.html', 'policy')]),
}

DATA['mca']['sources'].append(S('FHCDA definitions', 'https://www.nysenate.gov/legislation/laws/PBH/2994-A'))
