from common import entry as E, source as S
DATA = {
'foundations': E(
'''The California Board of Behavioral Sciences (BBS) regulates Licensed Clinical Social Workers (LCSWs) and Associate Clinical Social Workers (ASWs). Licensure, associate registration, supervision and employer duties must be distinguished. Use the current BBS statutes, regulations and guidance for the practice setting.

An ASW is not an independently licensed LCSW. A supervisor must meet the relevant requirements, and an employment title does not confer county-designated mental-health detention authority. NASW ethical material may inform practice but does not replace California licensing law.''',
['Confirm licence or registration status, practice setting and required supervision.', 'Explain the practitioner’s role, confidentiality limits and the purpose of the service.', 'Identify any separate statutory designation needed for assessment, reporting or detention work.', 'Use supervision and continuing education to address competence, bias and the person’s feedback.'],
'BBS investigates relevant professional complaints; county services, benefit agencies and courts address other decisions. Explain which route can address the person’s concern rather than presenting professional discipline as a service appeal.',
'An associate is asked to provide unsupervised clinical services because a manager believes the social-work degree is sufficient.',
'Check the registration and supervision rules for the setting and arrange a compliant service. Explain the practitioner’s status accurately and escalate any pressure to exceed scope. Keep urgent support within the role while ensuring the appropriate licensed oversight.',
'Equating a degree, associate registration and independent clinical licensure.',
[S('BBS role and regulated professions', 'https://www.bbs.ca.gov/about/board_info.html', 'professional-standards'), S('BBS LCSW and ASW requirements', 'https://bbs.ca.gov/applicants/lcsw.html', 'professional-standards'), S('BBS law changes', 'https://www.bbs.ca.gov/about/law_reg.html', 'professional-standards')]),
'care-support': E(
'''In-Home Supportive Services (IHSS) provides assessed in-home assistance to eligible aged, blind or disabled people. County assessment, authorised tasks and hours, financial or programme eligibility and actual provider arrangements are separate decisions. Medi-Cal services, regional-centre support and housing assistance have other rules.

An IHSS Notice of Action explains the county decision and hearing rights. A disagreement about authorised hours is different from a problem recruiting a worker or a complaint about missed visits. Identify the disputed decision and the evidence relevant to it.''',
['Apply through the appropriate county and identify the current eligibility and health-certification requirements.', 'Describe functional needs, actual assistance required and the home environment during assessment.', 'Check the authorised tasks, hours, notice and how a provider will be arranged.', 'Track the hearing or review route and any request concerning continued benefits while a decision is challenged.'],
'CDSS State Hearings handles relevant disputes, including IHSS decisions. Read the notice for the applicable deadline and any earlier action needed to seek continued assistance. A provider complaint does not automatically preserve a benefit-hearing deadline.',
'A recipient’s hours are reduced while their support needs have increased, and the family is told only to find a more efficient worker.',
'Obtain the assessment and Notice of Action, compare authorised tasks with current evidence and assist with the appropriate hearing request if wanted. Address immediate care gaps separately. Staffing difficulties should not obscure a dispute about the assessment itself.',
'Treating worker availability as proof that the assessed need has disappeared.',
[S('CDSS IHSS programme', 'https://www.cdss.ca.gov/in-home-supportive-services', 'policy'), S('CDSS State Hearing requests', 'https://www.cdss.ca.gov/hearing-requests', 'policy'), S('HCBS grievances and hearing rights', 'https://www.dhcs.ca.gov/services/home-and-community-based-services-hcbs-grievance-and-hearings/', 'policy')]),
'mca': E(
'''California’s Probate Code provides decision-specific capacity and healthcare decision-making provisions, including advance healthcare directives, agents and surrogate arrangements. Probate conservatorship and Lanterman-Petris-Short (LPS) conservatorship are different processes; neither should be described simply as a family member taking over all decisions.

Read the directive, power or court order and identify the exact authority. Financial power does not automatically include healthcare. Where no existing authorised decision-maker is available, use the applicable Probate Code surrogate process with the responsible healthcare provider rather than assuming an informal next-of-kin hierarchy.''',
['Identify the specific healthcare, personal or financial decision and support the person’s participation.', 'Check the relevant capacity standard and evidence rather than relying on diagnosis alone.', 'Read the advance directive, appointment or court order and verify scope and operation.', 'Use the applicable surrogate or court route if authority is missing or disputed.'],
'California Courts explains advance planning and conservatorship routes. A clinical consent dispute and a conservatorship petition have different procedures. Seek the relevant legal or clinical advice and preserve the person’s wishes and participation.',
'A relative with financial power of attorney signs for treatment while the patient’s healthcare directive names a different agent.',
'Check the patient’s own capacity for the treatment, then the directive and the agent’s operative authority. The financial document does not settle healthcare consent. Resolve the discrepancy through the responsible clinical and legal process before treating the signature as valid authority.',
'Assuming financial authority, next-of-kin status or a conservatorship label answers every consent question.',
[S('California Courts: advance care planning', 'https://selfhelp.courts.ca.gov/wills-estates-probate/legal-documents', 'policy'), S('Probate Code, healthcare decision-makers', 'https://leginfo.legislature.ca.gov/faces/codes_displaySection.xhtml?lawCode=PROB&sectionNum=4712.'), S('Probate Code, capacity presumption', 'https://leginfo.legislature.ca.gov/faces/codes_displaySection.xhtml?lawCode=PROB&sectionNum=810.')]),
'dols': E(
'''The LPS framework provides particular mental-health detention and conservatorship routes. Probate conservatorship, healthcare consent and facility restraint rules are separate. An admission agreement or conservator’s general status does not explain every locked-door measure, restraint or treatment.

A section 5150 hold is a time-limited assessment and crisis-intervention route, not an automatic order to keep someone for the whole maximum period or to impose every proposed treatment. Continuing detention requires the applicable further authority and safeguards.''',
['Identify the actual restriction, setting and the legal measure relied on.', 'Read the hold, court order or specific restraint authority and check its scope and expiry.', 'Distinguish the person’s detention status from medication consent and other healthcare decisions.', 'Arrange patients’ rights support, the appropriate hearing or court route and a plan to reduce restrictions.'],
'County patients’ rights advocates and legal representatives help with applicable detention and treatment rights. Certification review and medication-capacity hearings address different questions. Explain the route relevant to the person’s objection rather than describing every challenge as the same appeal.',
'A facility says a person on an assessment hold cannot object to any medication or restraint because they are already detained.',
'Identify the separate authority and safeguards for each intervention. Explain the person’s rights and connect them with the appropriate advocate or attorney. Review necessity and less restrictive options; the hold does not supply a universal treatment or restraint permission.',
'Treating detention, medication capacity and restraint authorisation as a single decision.',
[S('Welfare and Institutions Code, section 5150', 'https://leginfo.legislature.ca.gov/faces/codes_displaySection.xhtml?lawCode=WIC&sectionNum=5150.'), S('DHCS patients’ rights', 'https://www.dhcs.ca.gov/services/patients-rights/', 'policy'), S('Mental-health rights handbook', 'https://www.dhcs.ca.gov/wp-content/uploads/2025/10/DHCS_Handbook_English.pdf', 'policy')]),
'mha': E(
'''The Lanterman-Petris-Short framework in the Welfare and Institutions Code includes section 5150 assessment and crisis intervention, subsequent certification routes and conservatorship. Section 5150 permits specified authorised persons to act on probable cause under the statutory conditions, for up to 72 hours. It is not a power held by every social worker.

SB 43 expanded the grave-disability definition to include specified circumstances involving severe substance use disorder and inability to meet needs including personal safety or necessary medical care. Counties could defer implementation only until January 2026. Use the current section 5008 wording and criteria rather than an older food-clothing-shelter-only summary.''',
['Identify the authorised person, proposed route and evidence for the current statutory criteria.', 'Consider voluntary crisis support and whether the person can be served without detention.', 'Check the start time, required assessment, notices and any further certification or court process.', 'Keep detention and treatment-consent safeguards separate, including medication-capacity procedures where applicable.'],
'Explain access to the patients’ rights advocate, legal representation and the relevant hearing or court review. Additional detention is not automatic when an initial period ends. A broad social problem or lack of housing should not be substituted for the required statutory analysis.',
'A team uses an old training sheet to exclude personal safety and necessary medical care from a grave-disability assessment.',
'Check the current section 5008 definition and DHCS SB 43 guidance. Record the evidence connecting the qualifying condition to the inability to meet the relevant needs, consider available support and preserve the person’s review rights. The expanded definition still requires an individual legal assessment.',
'Using a superseded grave-disability definition or assuming all social workers can initiate a hold.',
[S('Section 5150', 'https://leginfo.legislature.ca.gov/faces/codes_displaySection.xhtml?lawCode=WIC&sectionNum=5150.'), S('Section 5008 definitions', 'https://leginfo.legislature.ca.gov/faces/codes_displaySection.xhtml?lawCode=WIC&sectionNum=5008.'), S('DHCS SB 43 guidance', 'https://www.dhcs.ca.gov/wp-content/uploads/2025/10/SB-43-FAQs.pdf', 'policy')]),
'safeguarding': E(
'''California’s Elder Abuse and Dependent Adult Civil Protection Act includes mandated-reporting duties. Welfare and Institutions Code section 15630 addresses covered reporters and circumstances. County APS service eligibility and the statutory definitions used for reporting should be checked separately; an agency’s service age range should not be substituted for the legal definition.

Community, long-term-care, state-hospital and other institutional concerns can have different reporting recipients and timing rules. CDSS publishes general reporting guidance, but the actual setting and allegation determine which statutory provisions apply.''',
['Identify the person’s statutory category, your reporting role, the alleged harm and the setting.', 'Make the required report through the correct APS, law-enforcement, ombudsman or other specified route.', 'Check the applicable telephone and written or electronic follow-up deadlines; do not assume one rule covers every institution.', 'Arrange immediate safety, consent-sensitive support and follow-up while preserving the adult’s account.'],
'A mandated report and the adult’s consent to ongoing services are different matters. Reporting does not itself appoint a conservator or authorise forced placement. Explain the relevant APS, regulatory, police or court process and available advocacy.',
'A worker reports suspected financial abuse to a supervisor and assumes that an internal form satisfies the legal duty.',
'Check section 15630 and the setting-specific reporting route, make the required external report and document timing and recipient. Address the adult’s access to money and essential support. Internal reporting can support compliance but does not replace it.',
'Confusing APS service eligibility with statutory reporting definitions or treating an internal report as sufficient.',
[S('CDSS mandated adult-abuse reporting', 'https://www.cdss.ca.gov/inforesources/cdss-programs/adult-protective-services/information-for-mandated-reporters', 'policy'), S('Welfare and Institutions Code, section 15630', 'https://leginfo.legislature.ca.gov/faces/codes_displaySection.xhtml?lawCode=WIC&sectionNum=15630.'), S('CDSS Adult Protective Services', 'https://cdss.ca.gov/adult-protective-services', 'policy')]),
'children': E(
'''The Child Abuse and Neglect Reporting Act (CANRA) specifies mandated reporters, reportable concerns and recipients. Penal Code section 11166 requires a covered reporter acting professionally or within employment to report knowledge or reasonable suspicion of child abuse or neglect. Certainty or medical proof is not required.

The ordinary procedure requires an initial telephone report immediately or as soon as practicably possible and a written follow-up within 36 hours. Reporting to a supervisor is not a substitute. Use the current statutory recipient and procedure, including any applicable special circumstances.''',
['Identify your mandated-reporter role and the facts supporting knowledge or reasonable suspicion.', 'Make the required report to an authorised receiving agency and address immediate danger.', 'Complete the follow-up within the applicable time and record what was reported.', 'Coordinate support and assess any dependency-court or Indian Child Welfare Act requirements where relevant.'],
'Explain confidentiality limits and the child’s and family’s access to support or legal advice. A mandated report does not itself establish the legal grounds for removal or a court finding. Preserve the distinction between suspicion, investigation and adjudication.',
'A child discloses abuse and a manager directs the worker to wait for internal approval before calling the receiving agency.',
'Apply the reporting threshold and act within the statutory procedure without allowing internal approval to delay the duty. Record the child’s words, the report and immediate safety actions. Avoid conducting a separate investigation to obtain proof before reporting.',
'Waiting for certainty or a manager’s permission before making a required CANRA report.',
[S('Penal Code, section 11166', 'https://leginfo.legislature.ca.gov/faces/codes_displaySection.xhtml?lawCode=PEN&sectionNum=11166.'), S('Penal Code, mandated-reporter categories', 'https://leginfo.legislature.ca.gov/faces/codes_displaySection.xhtml?lawCode=PEN&sectionNum=11165.7.')]),
'rights': E(
'''Federal disability and civil-rights requirements and California protections apply according to the service and decision. For confidentiality, distinguish HIPAA-covered entities, California’s Confidentiality of Medical Information Act and other applicable state rules. A social-work record is not automatically governed by HIPAA solely because it contains sensitive information.

Certain substance-use-disorder records have additional protection under 42 CFR Part 2. HHS states that compliance with the 2024 Part 2 changes was required by 16 February 2026. Use current guidance, including restrictions concerning legal proceedings, rather than treating ordinary treatment sharing as permission for every disclosure.''',
['Identify the organisation, service and applicable state and federal rights or privacy duties.', 'Arrange disability access, interpretation and culturally responsive participation.', 'Check the legal basis for disclosure and whether specially protected records or proceedings are involved.', 'Explain access, correction, complaints and any applicable patient-rights or legal review route.'],
'HHS Office for Civil Rights handles covered HIPAA and Part 2 complaints; California and professional complaint routes address other matters. A subpoena, a court order and a routine agency request need distinct analysis. Seek appropriate advice rather than automatically releasing a complete file.',
'A court-related request seeks a client’s substance-use treatment record, and a worker relies on a general treatment-sharing consent.',
'Check whether Part 2 applies and what the request, consent and current law permit for proceedings. Consider California requirements separately and seek the necessary advice. Document the disclosure decision and limit any release to what is lawfully authorised.',
'Assuming HIPAA applies to every record or that a general consent covers all uses in legal proceedings.',
[S('HHS mental and behavioural health privacy guidance', 'https://www.hhs.gov/hipaa/for-professionals/special-topics/mental-health/index.html', 'policy'), S('Current Part 2 confidentiality requirements', 'https://www.hhs.gov/hipaa/part-2/index.html', 'policy'), S('California Civil Code, medical-information disclosure', 'https://leginfo.legislature.ca.gov/faces/codes_displaySection.xhtml?lawCode=CIV&sectionNum=56.10.')]),
}
