// Fictional learning prompts only. Each monthly selection still requires moderator approval.
const scenarios=[
  ['Listening before planning','Alex says that the support plan does not reflect what matters to them. A meeting is approaching and different people have different priorities.','How would you make space for Alex’s wishes? What information is missing? How would local guidance shape the next conversation?'],
  ['A student finding their voice','Sam, a student on placement, is uncertain about a practice decision but worries that asking a question will seem unprofessional.','What could Sam bring to supervision? How can a supervisor invite questions? Which local standards or placement expectations would you check?'],
  ['Making learning useful','Morgan attends a learning session but finds it difficult to explain how it could change their day-to-day work.','What would a useful reflection include? How could Morgan try one small improvement? What evidence might help them evaluate it?'],
  ['A meeting that everyone can access','A planned discussion involves people who have different communication preferences. The usual meeting format may leave one person unable to participate fully.','What would you ask before arranging the meeting? Which communication supports could be explored? How would you check understanding without making assumptions?'],
  ['When professionals disagree','Two professionals interpret the same fictional information differently. Both want a helpful outcome, but the disagreement is slowing down planning.','How would you separate evidence from assumptions? What would respectful challenge look like? Which local escalation or supervision routes would you check?'],
  ['Recording with care','Jordan is drafting a fictional practice note. Some statements are direct observations, some are reported by others and some are Jordan’s interpretation.','How could the note distinguish these clearly? How would the person’s perspective be represented? What local recording guidance would you consult?'],
  ['Culture, curiosity and assumptions','A practitioner realises that their usual explanation for a situation may overlook a family’s cultural context and experience of services.','What questions would support curiosity? How could the practitioner check their assumptions? What sources of culturally informed support might be appropriate locally?'],
  ['A resource worth sharing?','An online training page makes a confident claim but provides little detail about its sources, authors or intended practice location.','How would you assess its authority and relevance? What would you verify before recommending it? How would you explain its limitations to a learner?'],
  ['Keeping the person at the centre','Taylor wants more say in an upcoming support meeting. A relative and a professional have already suggested different plans, and Taylor feels unheard.','What would you ask Taylor first? How would you explore communication, consent and participation? Which local frameworks would you check before deciding any next steps?'],
  ['Learning across practice locations','A practitioner moves to a different country, state or province and notices that familiar terms are used differently.','What would they need to relearn? How would they find reliable local guidance? Which habits can transfer, and which assumptions need checking?'],
  ['Preparing for supervision','Casey has several learning questions and limited supervision time. They want the discussion to lead to clear, manageable next steps.','How would you choose priorities? What evidence or reflection would help? How could agreed learning actions be followed up?'],
  ['Reflecting on a small improvement','A fictional team changed the way it explains a service to new visitors. Feedback is mixed, and the team wants to learn rather than defend its first approach.','Whose feedback is missing? How would you assess whether the change helped? What would a thoughtful next version look like?']
];
export function monthlyScenario(month){
  const index=Number(month.slice(5,7))-1;
  if(!Number.isInteger(index)||index<0||index>11)throw new Error('Invalid scenario month.');
  const [title,story,prompts]=scenarios[index];
  return {title:`${title} — monthly practice discussion`,body:`FICTIONAL LEARNING SCENARIO\n\n${story}\n\nDiscussion prompts\n${prompts}\n\nPlease state the practice location you are drawing on. Discuss principles and learning only; do not share real case details. These prompts do not prescribe a legal or professional decision.`};
}
