import {weatherController,WEATHER_LABELS} from './weather-state.mjs';
import * as T from 'three';
import {createLandscape} from './landscape.js';
import {gardenAudio} from './walk-audio.js';
import {safeReturnPath} from './state.mjs';
import {WALK_SAVE_KEY,route,ROUTE_LENGTH,places,nearestRoute,groundHeight,canWalk,cleanWalkSave,inPond} from './walk-route.mjs';
const $=id=>document.getElementById(id),reduced=matchMedia('(prefers-reduced-motion: reduce)'),coarse=matchMedia('(pointer: coarse)');
let saved;try{saved=cleanWalkSave(JSON.parse(localStorage.getItem(WALK_SAVE_KEY)));}catch{saved=cleanWalkSave(null);}
const weather=weatherController(saved.weather,saved.weatherAuto);
let started=false,failed=false,still=saved.still||reduced.matches,guided=false,sitting=false,dirty=true,activePlace=0,walkT=0,guideDistance=0;
let yaw=0,pitch=-.015,guideLook=0,keys=new Set(),touchKeys=new Set(),drag=null,scene,camera,renderer,landscape;
let savedReturn;try{savedReturn=JSON.parse(sessionStorage.getItem('quietGarden.return'));if(!Number.isFinite(savedReturn?.at)||Date.now()-savedReturn.at>86400000)savedReturn=null;}catch{}
const returnPath=safeReturnPath(savedReturn?.url||'/',location.origin);
for(const id of['returnLink','fallbackReturn']){$(id).href=returnPath;$(id).addEventListener('click',()=>{try{sessionStorage.setItem('quietGarden.returning','yes');}catch{}});}
const audio=gardenAudio({onNotice:announce});let toastTimer;
function announce(message){$('status').textContent=message;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('status').textContent='',6500);}
function save(){try{localStorage.setItem(WALK_SAVE_KEY,JSON.stringify(saved));}catch{announce('Saving is unavailable. You can still enjoy this visit.');}}
function stopWalking(){audio.resetMotion();guided=false;keys.clear();touchKeys.clear();drag=null;updateControls();}
function updateControls(){if(!started)return;$('guideButton').setAttribute('aria-pressed',String(guided));$('guideButton').textContent=guided?'Pause the walk  Ⅱ':'Follow the path  →';$('pauseButton').disabled=!guided&&!keys.size&&!touchKeys.size;$('guideButton').disabled=still;$('sitButton').textContent=sitting?'Stand up':'Sit a while';$('sitButton').setAttribute('aria-pressed',String(sitting));$('walkState').textContent=still?'Still view · Choose a place on the map':sitting?'A moment to sit · Drag to look around':guided?'Following the path · Look around or pause':coarse.matches?'Hold arrows to walk · Drag the view to look':'Drag to look · W A S D / arrows · Q / E to turn';$('touchControls').hidden=!started||!coarse.matches||still||sitting;$('controlHint').textContent=still?'Still mode · Six places to pause.':guided?'Escape or Pause stops the walk.':'Walk at your own pace. No scores. No rush.';}
function fail(reason){failed=true;stopWalking();audio.pause();$('fallback').hidden=false;$('fallbackReason').textContent=reason;$('intro').hidden=true;$('walkHud').hidden=true;$('gardenFooter').hidden=true;$('interaction').hidden=true;$('touchControls').hidden=true;$('mapPanel').hidden=true;$('weatherPanel').hidden=true;$('weatherButton').disabled=true;$('reticle').hidden=true;}
$('retryButton').onclick=()=>location.reload();
$('helpButton').onclick=()=>{stopWalking();$('helpDialog').showModal();};
for(const id of['closeHelp','doneHelp'])$(id).onclick=()=>$('helpDialog').close();
$('soundButton').onclick=async()=>{const button=$('soundButton');button.disabled=true;try{const on=await audio.toggle();button.setAttribute('aria-pressed',String(on));button.querySelector('span').textContent=on?'Sound on':'Sound off';}catch{button.setAttribute('aria-pressed','false');button.querySelector('span').textContent='Sound off';audio.pause();announce('Sound isn’t available in this browser. You can keep exploring.');}finally{button.disabled=false;}};
try{renderer=new T.WebGLRenderer({antialias:true,powerPreference:'low-power'});}catch{fail('This browser couldn’t open the 3D walk. You can still take a moment here.');}
if(renderer){try{init();}catch(error){console.error('Garden walk setup failed',error);fail('The garden couldn’t finish loading. Try again, or return to your learning.');}}
function init(){
 const mobile=innerWidth<=760;renderer.setPixelRatio(Math.min(devicePixelRatio,mobile?1.25:1.5));renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFShadowMap;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.outputColorSpace=T.SRGBColorSpace;$('world').append(renderer.domElement);
 const canvas=renderer.domElement;canvas.tabIndex=0;canvas.setAttribute('aria-label','Garden walk. Use W A S D or arrows to walk, Q and E to turn, or use Follow the path and the map.');canvas.setAttribute('role','region');canvas.addEventListener('webglcontextlost',e=>{e.preventDefault();fail('The 3D view was interrupted. Reload to return to the garden.');});
 scene=new T.Scene();camera=new T.PerspectiveCamera(62,innerWidth/innerHeight,.08,220);camera.rotation.order='YXZ';
 landscape=createLandscape(scene,renderer,mobile);landscape.setWeather(weather.snapshot());
 function headingAt(t){const here=route.getPointAt((t+1)%1),ahead=route.getPointAt((t+.016+1)%1);return Math.atan2(here.x-ahead.x,here.z-ahead.z);}
 function positionAt(t){const p=route.getPointAt(t);camera.position.set(p.x,groundHeight(p.x,p.z)+1.67,p.z);yaw=headingAt(t);pitch=-.015;camera.rotation.set(pitch,yaw,0);walkT=t;dirty=true;}
 positionAt(0);
 function setTheme(name){saved.theme=name;landscape.setTheme(name);document.querySelectorAll('[data-theme]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.theme===name)));dirty=true;save();}
 document.querySelectorAll('[data-theme]').forEach(b=>b.onclick=()=>setTheme(b.dataset.theme));landscape.setTheme(saved.theme);document.querySelectorAll('[data-theme]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.theme===saved.theme)));
 function weatherUi(){const state=weather.snapshot();document.querySelectorAll('[data-weather]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.weather===state.selected)));$('weatherAuto').checked=saved.weatherAuto;$('weatherAuto').disabled=still;$('weatherNote').textContent=still?'Still mode pauses weather animation and automatic changes.':'Changes about every two minutes during your visit.';$('weatherStatus').textContent=(state.transitioning&&!still?'Changing to ':'')+WEATHER_LABELS[state.selected]+(still?' · still view':'');$('weatherButton').setAttribute('aria-label',`Weather: ${WEATHER_LABELS[state.selected]}`);}
 function closeWeather(){ $('weatherPanel').hidden=true;$('weatherButton').setAttribute('aria-expanded','false');}
 $('weatherButton').onclick=()=>{const opening=$('weatherPanel').hidden;stopWalking();toggleMap(false);$('weatherPanel').hidden=!opening;$('weatherButton').setAttribute('aria-expanded',String(opening));if(opening)$('closeWeather').focus({preventScroll:true});};
 $('closeWeather').onclick=()=>{closeWeather();$('weatherButton').focus({preventScroll:true});};
 document.querySelectorAll('[data-weather]').forEach(b=>b.onclick=()=>{saved.weather=b.dataset.weather;weather.choose(saved.weather,still);landscape.setWeather(weather.snapshot());dirty=true;save();weatherUi();});
 $('weatherAuto').onchange=()=>{saved.weatherAuto=$('weatherAuto').checked;weather.setAutomatic(saved.weatherAuto);save();weatherUi();};weatherUi();
 $('speedSelect').value=String(saved.pace);$('speedSelect').onchange=()=>{saved.pace=Number($('speedSelect').value);save();};
 function setStill(value){still=value;saved.still=still;stopWalking();$('motionButton').setAttribute('aria-pressed',String(still));$('reticle').hidden=still||!started;dirty=true;save();updateControls();weatherUi();}
 $('motionButton').onclick=()=>setStill(!still);$('motionButton').setAttribute('aria-pressed',String(still));reduced.addEventListener('change',e=>{if(e.matches)setStill(true);});
 $('enterButton').onclick=()=>{started=true;$('intro').hidden=true;$('walkHud').hidden=false;$('reticle').hidden=still;document.body.classList.add('playing');updateLocation();updateControls();(still?$('nextButton'):$('guideButton')).focus({preventScroll:true});};
 function joinPath(){stopWalking();sitting=false;const near=nearestRoute(camera.position.x,camera.position.z);walkT=near.t;const p=route.getPointAt(walkT);camera.position.set(p.x,groundHeight(p.x,p.z)+1.67,p.z);yaw=headingAt(walkT);pitch=-.015;guideLook=0;guided=true;guideDistance=0;dirty=true;updateControls();}
 $('guideButton').onclick=()=>{if(still)return;if(guided)stopWalking();else joinPath();};$('pauseButton').onclick=stopWalking;
 function arrive(index){stopWalking();sitting=false;positionAt(places[index].t);if(index===2){yaw=Math.PI;pitch=-.07;}updateLocation();updateControls();announce(places[index].name+'. Take your time.');}
 $('nextButton').onclick=()=>{const current=nearestRoute(camera.position.x,camera.position.z).t;let next=0,best=2;places.forEach((p,i)=>{const d=(p.t-current+1)%1;if(d>.025&&d<best){best=d;next=i;}});arrive(next);};
 let standingPosition=null;
 function toggleSit(){stopWalking();if(sitting){sitting=false;if(standingPosition)camera.position.copy(standingPosition);standingPosition=null;}else{standingPosition=camera.position.clone();sitting=true;const b=landscape.benches.find(b=>Math.hypot(camera.position.x-b.x,camera.position.z-b.z)<8);if(b){camera.position.set(b.x,groundHeight(b.x,b.z)+1.08,b.z);yaw=b.angle+Math.PI;pitch=0;}else camera.position.y=groundHeight(camera.position.x,camera.position.z)+1.05;announce('A moment to sit. Stand up whenever you’re ready.');}dirty=true;updateControls();}
 $('sitButton').onclick=toggleSit;
 function toggleMap(open){stopWalking();if(open)closeWeather();$('mapPanel').hidden=!open;$('mapButton').setAttribute('aria-expanded',String(open));if(open)$('closeMap').focus({preventScroll:true});}
 $('mapButton').onclick=()=>toggleMap($('mapPanel').hidden);$('closeMap').onclick=()=>{toggleMap(false);$('mapButton').focus({preventScroll:true});};
 $('mapPath').setAttribute('d',Array.from({length:121},(_,i)=>{const p=route.getPointAt(i/120);return `${i?'L':'M'}${p.x.toFixed(2)},${p.z.toFixed(2)}`;}).join(' ')+' Z');
 places.forEach((p,i)=>{const point=route.getPointAt(p.t),dot=document.createElementNS('http://www.w3.org/2000/svg','circle');dot.setAttribute('cx',point.x);dot.setAttribute('cy',point.z);dot.setAttribute('r','1.1');dot.setAttribute('fill','#c5cba8');$('mapStops').append(dot);const b=document.createElement('button');b.textContent=p.name;b.dataset.place=String(i);b.onclick=()=>{arrive(i);toggleMap(false);$('nextButton').focus({preventScroll:true});};$('mapPlaces').append(b);});
 function updateLocation(){const near=nearestRoute(camera.position.x,camera.position.z);let d=Infinity;places.forEach((p,i)=>{const n=Math.abs(p.t-near.t),delta=Math.min(n,1-n);if(delta<d){d=delta;activePlace=i;}});const current=places[activePlace];$('placeName').textContent=current.name;$('placeDescription').textContent=current.description;$('mapDot').setAttribute('cx',camera.position.x.toFixed(3));$('mapDot').setAttribute('cy',camera.position.z.toFixed(3));document.querySelectorAll('[data-place]').forEach(b=>b.setAttribute('aria-current',String(Number(b.dataset.place)===activePlace)));const p=route.getPointAt(current.t);$('interaction').hidden=!started||Math.hypot(camera.position.x-p.x,camera.position.z-p.z)>8;$('interactButton').textContent=current.action;$('interactionDescription').textContent=current.description;}
 function interactAt(index){stopWalking();if(places[index].kind==='bench'&&!sitting)toggleSit();else{if(!saved.opened.includes(index)){saved.opened.push(index);save();}landscape.interact(index,still);audio.interact(places[index].kind,still);}dirty=true;announce(places[index].kind==='water'&&still?'Still water. Notice the reflections.':places[index].note);}
 $('interactButton').onclick=()=>interactAt(activePlace);

 const moves={KeyW:'forward',ArrowUp:'forward',KeyS:'backward',ArrowDown:'backward',KeyA:'left',ArrowLeft:'left',KeyD:'right',ArrowRight:'right',KeyQ:'turnLeft',KeyE:'turnRight'};
 function acceptsMovement(e){return started&&!still&&!sitting&&!failed&&!$('helpDialog').open&&$('mapPanel').hidden&&$('weatherPanel').hidden&&!['INPUT','SELECT','TEXTAREA'].includes(e.target?.tagName);}
 window.addEventListener('keydown',e=>{if(e.code==='Escape'){stopWalking();if(!$('mapPanel').hidden)toggleMap(false);if(!$('weatherPanel').hidden){closeWeather();$('weatherButton').focus({preventScroll:true});}return;}const key=moves[e.code];if(!key||!acceptsMovement(e))return;e.preventDefault();if(guided)stopWalking();keys.add(key);updateControls();});
 window.addEventListener('keyup',e=>{if(moves[e.code]){keys.delete(moves[e.code]);updateControls();}});
 document.querySelectorAll('[data-move]').forEach(b=>{b.addEventListener('pointerdown',e=>{if(still||sitting)return;e.preventDefault();if(guided)stopWalking();b.setPointerCapture(e.pointerId);touchKeys.add(b.dataset.move);updateControls();});for(const name of['pointerup','pointercancel','lostpointercapture'])b.addEventListener(name,()=>{touchKeys.delete(b.dataset.move);updateControls();});});
 canvas.addEventListener('pointerdown',e=>{if(!started||still)return;canvas.focus({preventScroll:true});canvas.setPointerCapture(e.pointerId);drag={id:e.pointerId,x:e.clientX,y:e.clientY,total:0};});
 canvas.addEventListener('pointermove',e=>{if(!drag||drag.id!==e.pointerId||still)return;const dx=e.clientX-drag.x,dy=e.clientY-drag.y;drag.total+=Math.abs(dx)+Math.abs(dy);drag.x=e.clientX;drag.y=e.clientY;if(guided)guideLook=T.MathUtils.clamp(guideLook-dx*.004,-1.4,1.4);else yaw-=dx*.004;pitch=T.MathUtils.clamp(pitch-dy*.003,-.75,.65);dirty=true;});
 const ray=new T.Raycaster(),pointer=new T.Vector2();canvas.addEventListener('pointerup',e=>{if(drag?.total<6){const rect=canvas.getBoundingClientRect();pointer.set((e.clientX-rect.left)/rect.width*2-1,-(e.clientY-rect.top)/rect.height*2+1);ray.setFromCamera(pointer,camera);const hit=ray.intersectObjects(landscape.hitTargets,true).find(h=>h.distance<13);if(hit){let obj=hit.object;while(obj&&obj.userData.placeIndex===undefined)obj=obj.parent;if(obj)interactAt(obj.userData.placeIndex);}}drag=null;});for(const event of['pointercancel','lostpointercapture'])canvas.addEventListener(event,()=>{drag=null;});
 window.addEventListener('blur',()=>{stopWalking();audio.pause();});window.addEventListener('focus',()=>{if(!document.hidden&&!failed)audio.resume();});
 document.addEventListener('visibilitychange',()=>{if(document.hidden){stopWalking();audio.pause();}else if(!failed){audio.resume();dirty=true;}});window.addEventListener('pagehide',()=>{stopWalking();audio.pause();});
 function resize(){renderer.setSize(innerWidth,innerHeight);camera.aspect=innerWidth/innerHeight;camera.fov=innerWidth<600?68:62;camera.updateProjectionMatrix();dirty=true;updateControls();}
 window.addEventListener('resize',resize);coarse.addEventListener('change',updateControls);resize();updateLocation();
 function move(dt){let changed=false;if(guided){const step=saved.pace*dt;walkT=(walkT+step/ROUTE_LENGTH)%1;guideDistance+=step;const p=route.getPointAt(walkT);camera.position.set(p.x,groundHeight(p.x,p.z)+1.67,p.z);const target=headingAt(walkT)+guideLook,angle=Math.atan2(Math.sin(target-yaw),Math.cos(target-yaw));yaw+=angle*Math.min(1,dt*3);changed=true;if(guideDistance>=ROUTE_LENGTH){stopWalking();announce('A full circle. Stay a little, or return whenever you’re ready.');}}
  const pressed=new Set([...keys,...touchKeys]);if(!sitting&&pressed.size){if(pressed.has('turnLeft'))yaw+=dt*.8;if(pressed.has('turnRight'))yaw-=dt*.8;const forward=Number(pressed.has('forward'))-Number(pressed.has('backward')),side=Number(pressed.has('right'))-Number(pressed.has('left')),length=Math.hypot(forward,side)||1,step=saved.pace*dt;const dx=(-Math.sin(yaw)*forward+Math.cos(yaw)*side)/length*step,dz=(-Math.cos(yaw)*forward-Math.sin(yaw)*side)/length*step;const x=camera.position.x,z=camera.position.z;if(canWalk(x+dx,z+dz,landscape.obstacles)){camera.position.x+=dx;camera.position.z+=dz;}else if(canWalk(x+dx,z,landscape.obstacles))camera.position.x+=dx;else if(canWalk(x,z+dz,landscape.obstacles))camera.position.z+=dz;camera.position.y=groundHeight(camera.position.x,camera.position.z)+1.67;changed=true;}return changed;}
 let last=0,lastRender=0,animationTime=0,locationTimer=0;
 function frame(now){requestAnimationFrame(frame);if(failed||document.hidden){last=now;return;}if(now-lastRender<32)return;const elapsedFrame=Math.min((now-last)/1000,.5)||.016,dt=Math.min(elapsedFrame,.05);last=now;lastRender=now;if(!still)animationTime+=dt;const weatherState=weather.tick(elapsedFrame,{still,active:started});if(weatherState.changed){saved.weather=weatherState.selected;save();weatherUi();}landscape.setWeather(weatherState);const oldX=camera.position.x,oldZ=camera.position.z;if(started&&!still)dirty=move(dt)||dirty;const near=nearestRoute(camera.position.x,camera.position.z),surface=inPond(camera.position.x,camera.position.z,1.55)&&near.distance<1.65?'wood':near.distance<=1.65?'gravel':'grass';audio.update({distance:started&&!still?Math.hypot(camera.position.x-oldX,camera.position.z-oldZ):0,dt,surface,x:camera.position.x,z:camera.position.z,yaw,still,rain:weatherState.rain});if(still&&!dirty)return;camera.rotation.set(pitch,yaw,0);landscape.update(animationTime,dt,camera,still,saved.opened);renderer.render(scene,camera);dirty=false;locationTimer+=dt;if(locationTimer>.2){updateLocation();weatherUi();locationTimer=0;}}
 // Compile once before enabling entry, avoiding a shader compilation stall mid-walk.
 renderer.compile(scene,camera);renderer.render(scene,camera);$('enterButton').disabled=false;$('enterButton').textContent='Begin your garden walk  →';document.body.dataset.gardenReady='true';requestAnimationFrame(frame);
}
